USE [HPIMES]
GO

/****** Object:  Index [IDX_Part_BomNodeType_Flag]    Script Date: 04/05/2014 08:27:37 ******/
CREATE NONCLUSTERED INDEX [IDX_Part_BomNodeType_Flag] ON [dbo].[Part] 
(
	[BomNodeType] ASC,
	[Flag] ASC
)
INCLUDE ( [Descr],
[PartNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

