//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.UPSPrimaryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hp.com/", ConfigurationName="UPSPrimaryService.UPSPrimaryServiceSoap")]
    public interface UPSPrimaryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendBOMAndPOLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendBOMAndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string BOM, bool FinalBOM, int FinalQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendBOMWithCTO5AndPOLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendBOMWithCTO5AndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string CTO5, string BOM, bool FinalBOM, int FinalQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendAllAndPOLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendAllAndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string CT05, string BOM, string OSI, bool FinalBOM, int FinalQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetCISServices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet UPSGetCISServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetUPSServices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet UPSGetUPSServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetSupportedAV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet UPSGetSupportedAV(System.DateTime cutoffdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSCancelPO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSCancelPO(string HP_PO_Num, string CustPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSVerifyPOReady", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSVerifyPOReady(string HP_PO_Num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetOSI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSGetOSI(string HP_PO_Num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendOSI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendOSI(string TransID, string HP_PO_Num, string orderinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendAll(string TransID, string HP_PO_Num, string CustPO, int Qty, string CT05, string BOM, string OSI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendBOM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendBOM(string TransID, string HP_PO_Num, string CustPO, int Qty, string BOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSSendBOMWithCTO5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSSendBOMWithCTO5(string TransID, string HP_PO_Num, string CustPO, int Qty, string CT05, string BOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetPrintRouting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSGetPrintRouting(string PartNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/UPSGetPrintRoutingAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UPS.UPSPrimaryService.BomStatus UPSGetPrintRoutingAll(string HPPO);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hp.com/")]
    public partial class BomStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retcodeField;
        
        private string messageField;
        
        private string datastringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retcode {
            get {
                return this.retcodeField;
            }
            set {
                this.retcodeField = value;
                this.RaisePropertyChanged("retcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string datastring {
            get {
                return this.datastringField;
            }
            set {
                this.datastringField = value;
                this.RaisePropertyChanged("datastring");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface UPSPrimaryServiceSoapChannel : UPS.UPSPrimaryService.UPSPrimaryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UPSPrimaryServiceSoapClient : System.ServiceModel.ClientBase<UPS.UPSPrimaryService.UPSPrimaryServiceSoap>, UPS.UPSPrimaryService.UPSPrimaryServiceSoap {
        
        public UPSPrimaryServiceSoapClient() {
        }
        
        public UPSPrimaryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPSPrimaryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSPrimaryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSPrimaryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendBOMAndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string BOM, bool FinalBOM, int FinalQty) {
            return base.Channel.UPSSendBOMAndPOLine(TransID, HP_PO_Num, POLine, CustPO, Qty, BOM, FinalBOM, FinalQty);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendBOMWithCTO5AndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string CTO5, string BOM, bool FinalBOM, int FinalQty) {
            return base.Channel.UPSSendBOMWithCTO5AndPOLine(TransID, HP_PO_Num, POLine, CustPO, Qty, CTO5, BOM, FinalBOM, FinalQty);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendAllAndPOLine(string TransID, string HP_PO_Num, int POLine, string CustPO, int Qty, string CT05, string BOM, string OSI, bool FinalBOM, int FinalQty) {
            return base.Channel.UPSSendAllAndPOLine(TransID, HP_PO_Num, POLine, CustPO, Qty, CT05, BOM, OSI, FinalBOM, FinalQty);
        }
        
        public System.Data.DataSet UPSGetCISServices() {
            return base.Channel.UPSGetCISServices();
        }
        
        public System.Data.DataSet UPSGetUPSServices() {
            return base.Channel.UPSGetUPSServices();
        }
        
        public System.Data.DataSet UPSGetSupportedAV(System.DateTime cutoffdate) {
            return base.Channel.UPSGetSupportedAV(cutoffdate);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSCancelPO(string HP_PO_Num, string CustPO) {
            return base.Channel.UPSCancelPO(HP_PO_Num, CustPO);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSVerifyPOReady(string HP_PO_Num) {
            return base.Channel.UPSVerifyPOReady(HP_PO_Num);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSGetOSI(string HP_PO_Num) {
            return base.Channel.UPSGetOSI(HP_PO_Num);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendOSI(string TransID, string HP_PO_Num, string orderinfo) {
            return base.Channel.UPSSendOSI(TransID, HP_PO_Num, orderinfo);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendAll(string TransID, string HP_PO_Num, string CustPO, int Qty, string CT05, string BOM, string OSI) {
            return base.Channel.UPSSendAll(TransID, HP_PO_Num, CustPO, Qty, CT05, BOM, OSI);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendBOM(string TransID, string HP_PO_Num, string CustPO, int Qty, string BOM) {
            return base.Channel.UPSSendBOM(TransID, HP_PO_Num, CustPO, Qty, BOM);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSSendBOMWithCTO5(string TransID, string HP_PO_Num, string CustPO, int Qty, string CT05, string BOM) {
            return base.Channel.UPSSendBOMWithCTO5(TransID, HP_PO_Num, CustPO, Qty, CT05, BOM);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSGetPrintRouting(string PartNumber) {
            return base.Channel.UPSGetPrintRouting(PartNumber);
        }
        
        public UPS.UPSPrimaryService.BomStatus UPSGetPrintRoutingAll(string HPPO) {
            return base.Channel.UPSGetPrintRoutingAll(HPPO);
        }
    }
}
