// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Inventec.HPEDITS.XmlCreator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Inventec.HPEDITS.XmlCreator {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class HOUSE_WAYBILLS {
        
        private List<HOUSE_WAYBILLSHOUSE_WAYBILL> hOUSE_WAYBILLField;
        
        public HOUSE_WAYBILLS() {
            this.hOUSE_WAYBILLField = new List<HOUSE_WAYBILLSHOUSE_WAYBILL>();
        }
        
        public List<HOUSE_WAYBILLSHOUSE_WAYBILL> HOUSE_WAYBILL {
            get {
                return this.hOUSE_WAYBILLField;
            }
            set {
                this.hOUSE_WAYBILLField = value;
            }
        }
    }
    
    public partial class HOUSE_WAYBILLSHOUSE_WAYBILL {
        
        private string wAYBILL_NUMBERField;
        
        private string sHIP_MODEField;
        
        private string iNTL_CARRIERField;
        
        private string cURRENT_DATEField;
        
        private string aCTUAL_SHIPDATEField;
        
        private double hAWB_PALLET_QTYField;
        
        private double hAWB_BOX_QTYField;
        
        private double hAWB_UNIT_QTYField;
        
        private string cONSOL_INVOICEField;
        
        private string dUTY_CODEField;
        
        private string pREF_GATEWAYField;
        
        private string tRANS_SERV_LEVELField;
        
        private double hAWB_ACT_WEIGHTField;
        
        private double hAWB_GROSS_WEIGHTField;
        
        private string sHIP_FROM_NAMEField;
        
        private string sHIP_FROM_NAME_2Field;
        
        private string sHIP_FROM_NAME_3Field;
        
        private string sHIP_FROM_STREETField;
        
        private string sHIP_FROM_STREET_2Field;
        
        private string sHIP_FROM_CITYField;
        
        private string sHIP_FROM_STATEField;
        
        private string sHIP_FROM_ZIPField;
        
        private string sHIP_FROM_COUNTRY_NAMEField;
        
        private string sHIP_FROM_COUNTRY_CODEField;
        
        private string sHIP_FROM_CONTACTField;
        
        private string sHIP_FROM_TELEPHONEField;
        
        private string sHIP_TO_IDField;
        
        private string sHIP_TO_NAMEField;
        
        private string sHIP_TO_NAME_2Field;
        
        private string sHIP_TO_NAME_3Field;
        
        private string sHIP_TO_STREETField;
        
        private string sHIP_TO_STREET_2Field;
        
        private string sHIP_TO_CITYField;
        
        private string sHIP_TO_STATEField;
        
        private string sHIP_TO_ZIPField;
        
        private string sHIP_TO_COUNTRY_CODEField;
        
        private string sHIP_TO_COUNTRY_NAMEField;
        
        private List<HOUSE_WAYBILLSHOUSE_WAYBILLPACK_ID_LINE_ITEM> pACK_ID_LINE_ITEMField;
        
        public HOUSE_WAYBILLSHOUSE_WAYBILL() {
            this.pACK_ID_LINE_ITEMField = new List<HOUSE_WAYBILLSHOUSE_WAYBILLPACK_ID_LINE_ITEM>();
        }
        
        public string WAYBILL_NUMBER {
            get {
                return this.wAYBILL_NUMBERField;
            }
            set {
                this.wAYBILL_NUMBERField = value;
            }
        }
        
        public string SHIP_MODE {
            get {
                return this.sHIP_MODEField;
            }
            set {
                this.sHIP_MODEField = value;
            }
        }
        
        public string INTL_CARRIER {
            get {
                return this.iNTL_CARRIERField;
            }
            set {
                this.iNTL_CARRIERField = value;
            }
        }
        
        public string CURRENT_DATE {
            get {
                return this.cURRENT_DATEField;
            }
            set {
                this.cURRENT_DATEField = value;
            }
        }
        
        public string ACTUAL_SHIPDATE {
            get {
                return this.aCTUAL_SHIPDATEField;
            }
            set {
                this.aCTUAL_SHIPDATEField = value;
            }
        }
        
        public double HAWB_PALLET_QTY {
            get {
                return this.hAWB_PALLET_QTYField;
            }
            set {
                this.hAWB_PALLET_QTYField = value;
            }
        }
        
        public double HAWB_BOX_QTY {
            get {
                return this.hAWB_BOX_QTYField;
            }
            set {
                this.hAWB_BOX_QTYField = value;
            }
        }
        
        public double HAWB_UNIT_QTY {
            get {
                return this.hAWB_UNIT_QTYField;
            }
            set {
                this.hAWB_UNIT_QTYField = value;
            }
        }
        
        public string CONSOL_INVOICE {
            get {
                return this.cONSOL_INVOICEField;
            }
            set {
                this.cONSOL_INVOICEField = value;
            }
        }
        
        public string DUTY_CODE {
            get {
                return this.dUTY_CODEField;
            }
            set {
                this.dUTY_CODEField = value;
            }
        }
        
        public string PREF_GATEWAY {
            get {
                return this.pREF_GATEWAYField;
            }
            set {
                this.pREF_GATEWAYField = value;
            }
        }
        
        public string TRANS_SERV_LEVEL {
            get {
                return this.tRANS_SERV_LEVELField;
            }
            set {
                this.tRANS_SERV_LEVELField = value;
            }
        }
        
        public double HAWB_ACT_WEIGHT {
            get {
                return this.hAWB_ACT_WEIGHTField;
            }
            set {
                this.hAWB_ACT_WEIGHTField = value;
            }
        }
        
        public double HAWB_GROSS_WEIGHT {
            get {
                return this.hAWB_GROSS_WEIGHTField;
            }
            set {
                this.hAWB_GROSS_WEIGHTField = value;
            }
        }
        
        public string SHIP_FROM_NAME {
            get {
                return this.sHIP_FROM_NAMEField;
            }
            set {
                this.sHIP_FROM_NAMEField = value;
            }
        }
        
        public string SHIP_FROM_NAME_2 {
            get {
                return this.sHIP_FROM_NAME_2Field;
            }
            set {
                this.sHIP_FROM_NAME_2Field = value;
            }
        }
        
        public string SHIP_FROM_NAME_3 {
            get {
                return this.sHIP_FROM_NAME_3Field;
            }
            set {
                this.sHIP_FROM_NAME_3Field = value;
            }
        }
        
        public string SHIP_FROM_STREET {
            get {
                return this.sHIP_FROM_STREETField;
            }
            set {
                this.sHIP_FROM_STREETField = value;
            }
        }
        
        public string SHIP_FROM_STREET_2 {
            get {
                return this.sHIP_FROM_STREET_2Field;
            }
            set {
                this.sHIP_FROM_STREET_2Field = value;
            }
        }
        
        public string SHIP_FROM_CITY {
            get {
                return this.sHIP_FROM_CITYField;
            }
            set {
                this.sHIP_FROM_CITYField = value;
            }
        }
        
        public string SHIP_FROM_STATE {
            get {
                return this.sHIP_FROM_STATEField;
            }
            set {
                this.sHIP_FROM_STATEField = value;
            }
        }
        
        public string SHIP_FROM_ZIP {
            get {
                return this.sHIP_FROM_ZIPField;
            }
            set {
                this.sHIP_FROM_ZIPField = value;
            }
        }
        
        public string SHIP_FROM_COUNTRY_NAME {
            get {
                return this.sHIP_FROM_COUNTRY_NAMEField;
            }
            set {
                this.sHIP_FROM_COUNTRY_NAMEField = value;
            }
        }
        
        public string SHIP_FROM_COUNTRY_CODE {
            get {
                return this.sHIP_FROM_COUNTRY_CODEField;
            }
            set {
                this.sHIP_FROM_COUNTRY_CODEField = value;
            }
        }
        
        public string SHIP_FROM_CONTACT {
            get {
                return this.sHIP_FROM_CONTACTField;
            }
            set {
                this.sHIP_FROM_CONTACTField = value;
            }
        }
        
        public string SHIP_FROM_TELEPHONE {
            get {
                return this.sHIP_FROM_TELEPHONEField;
            }
            set {
                this.sHIP_FROM_TELEPHONEField = value;
            }
        }
        
        public string SHIP_TO_ID {
            get {
                return this.sHIP_TO_IDField;
            }
            set {
                this.sHIP_TO_IDField = value;
            }
        }
        
        public string SHIP_TO_NAME {
            get {
                return this.sHIP_TO_NAMEField;
            }
            set {
                this.sHIP_TO_NAMEField = value;
            }
        }
        
        public string SHIP_TO_NAME_2 {
            get {
                return this.sHIP_TO_NAME_2Field;
            }
            set {
                this.sHIP_TO_NAME_2Field = value;
            }
        }
        
        public string SHIP_TO_NAME_3 {
            get {
                return this.sHIP_TO_NAME_3Field;
            }
            set {
                this.sHIP_TO_NAME_3Field = value;
            }
        }
        
        public string SHIP_TO_STREET {
            get {
                return this.sHIP_TO_STREETField;
            }
            set {
                this.sHIP_TO_STREETField = value;
            }
        }
        
        public string SHIP_TO_STREET_2 {
            get {
                return this.sHIP_TO_STREET_2Field;
            }
            set {
                this.sHIP_TO_STREET_2Field = value;
            }
        }
        
        public string SHIP_TO_CITY {
            get {
                return this.sHIP_TO_CITYField;
            }
            set {
                this.sHIP_TO_CITYField = value;
            }
        }
        
        public string SHIP_TO_STATE {
            get {
                return this.sHIP_TO_STATEField;
            }
            set {
                this.sHIP_TO_STATEField = value;
            }
        }
        
        public string SHIP_TO_ZIP {
            get {
                return this.sHIP_TO_ZIPField;
            }
            set {
                this.sHIP_TO_ZIPField = value;
            }
        }
        
        public string SHIP_TO_COUNTRY_CODE {
            get {
                return this.sHIP_TO_COUNTRY_CODEField;
            }
            set {
                this.sHIP_TO_COUNTRY_CODEField = value;
            }
        }
        
        public string SHIP_TO_COUNTRY_NAME {
            get {
                return this.sHIP_TO_COUNTRY_NAMEField;
            }
            set {
                this.sHIP_TO_COUNTRY_NAMEField = value;
            }
        }
        
        public List<HOUSE_WAYBILLSHOUSE_WAYBILLPACK_ID_LINE_ITEM> PACK_ID_LINE_ITEM {
            get {
                return this.pACK_ID_LINE_ITEMField;
            }
            set {
                this.pACK_ID_LINE_ITEMField = value;
            }
        }
    }
    
    public partial class HOUSE_WAYBILLSHOUSE_WAYBILLPACK_ID_LINE_ITEM {
        
        private string pACK_IDField;
        
        private string hP_SOField;
        
        private double pACK_ID_LINE_ITEM_UNIT_QTYField;
        
        public string PACK_ID {
            get {
                return this.pACK_IDField;
            }
            set {
                this.pACK_IDField = value;
            }
        }
        
        public string HP_SO {
            get {
                return this.hP_SOField;
            }
            set {
                this.hP_SOField = value;
            }
        }
        
        public double PACK_ID_LINE_ITEM_UNIT_QTY {
            get {
                return this.pACK_ID_LINE_ITEM_UNIT_QTYField;
            }
            set {
                this.pACK_ID_LINE_ITEM_UNIT_QTYField = value;
            }
        }
    }
    
    public partial class UDFType {
        
        private string kEYField;
        
        private string vALUEField;
        
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
            }
        }
        
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
    }
}
