USE [HPIMES]
GO

/****** Object:  Index [Model_PK]    Script Date: 04/05/2014 08:25:34 ******/
ALTER TABLE [dbo].[Model] ADD  CONSTRAINT [Model_PK] PRIMARY KEY CLUSTERED 
(
	[Model] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

