USE [HPIMES]
GO

/****** Object:  Index [IX_Model_ModelStatus]    Script Date: 04/05/2014 08:25:26 ******/
CREATE NONCLUSTERED INDEX [IX_Model_ModelStatus] ON [dbo].[Model] 
(
	[Model] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

