USE [HPIMES]
GO

/****** Object:  Index [Part_PK]    Script Date: 04/05/2014 08:28:08 ******/
ALTER TABLE [dbo].[Part] ADD  CONSTRAINT [Part_PK] PRIMARY KEY CLUSTERED 
(
	[PartNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

