USE [HPIMES]
GO

/****** Object:  Index [ModelBOM_PK]    Script Date: 04/05/2014 08:24:57 ******/
ALTER TABLE [dbo].[ModelBOM] ADD  CONSTRAINT [ModelBOM_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

