USE [HPIMES]
GO

/****** Object:  Index [ModelInfo_PK]    Script Date: 04/05/2014 08:26:18 ******/
ALTER TABLE [dbo].[ModelInfo] ADD  CONSTRAINT [ModelInfo_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

