<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:param name="CURRENT_DATE_MAX" select="'15'"/>
	<xsl:param name="HP_PN_max" select="'20'"/>
	<xsl:param name="HP_SO_MAX" select="'30'"/>
	<xsl:param name="NumBoxPerPage" select="'81513927242118151512120909090606060606060303030303030303030303030303030303030303'"/>
	<xsl:param name="PACK_ID_MAX" select="'30'"/>
	<xsl:param name="WAYBILL_NUMBER_MAX" select="'30'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="default-page" page-height="8.27in" page-width="11.69in" margin-left="0.45cm" margin-right="0.45cm">
				<fo:region-body margin-top="0.45cm" margin-bottom="0.8cm"/>
				<fo:region-after extent="0.8cm"/>
			</fo:simple-page-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence master-reference="default-page" initial-page-number="1" format="1">
				<xsl:call-template name="footerall"/>
				<fo:flow flow-name="xsl-region-body">
					<fo:block>
						<xsl:for-each select="$XML">
							<xsl:for-each select="PACK_ID">
								<xsl:for-each select="PACK_ID_LINE_ITEM">
									<xsl:if test="position() &gt; 1">
										<fo:block break-after="page">
											<fo:leader leader-pattern="space"/>
										</fo:block>
									</xsl:if>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-body start-indent="0pt">
											<fo:table-row>
												<fo:table-cell border="none" number-columns-spanned="3" padding="2pt" display-align="before">
													<fo:block>
														<xsl:for-each select="BOX">
															<xsl:if test="position() mod number(substring($NumBoxPerPage,count(../BOX[1]/SERIAL_NUM)*2-1,2)) = 1">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" height="105pt" padding="2pt" text-align="left" display-align="center">
																				<fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline>
																						<xsl:text>PACK ID</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>AIR WAYBILL # </xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>HP SO# </xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>ITEM</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>PART NUMBER</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>CUSTOMER PO</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>CUSTOMER CONTACT</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>TOTAL BOXES</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>TOTAL UNITS</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>TOTAL NET WEIGHT</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																				<fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<xsl:for-each select="$XML">
																						<xsl:for-each select="PACK_ID">
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="substring( PACK_ID , 1 , $PACK_ID_MAX )"/>
																							</fo:inline>
																							<fo:block/>
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="substring( WAYBILL_NUMBER , 1 , $WAYBILL_NUMBER_MAX )"/>
																							</fo:inline>
																							<fo:block/>
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="substring( HP_SO , 1 , $HP_SO_MAX )"/>
																							</fo:inline>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																							<fo:block/>
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="PACK_ID_LINE_ITEM/HP_SO_LINE_ITEM"/>
																							</fo:inline>
																							<fo:block/>
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="PACK_ID_LINE_ITEM/HP_PN"/>
																							</fo:inline>
																							<fo:block/>
																							<fo:inline>
																								<xsl:text>: </xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:value-of select="CUST_PO"/>
																							</fo:inline>
																						</xsl:for-each>
																					</xsl:for-each>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>: </xsl:text>
																					</fo:inline>
																					<fo:inline>
																						<xsl:value-of select="../../SHIP_TO_NAME_2"/>
																					</fo:inline>
																					<fo:inline>
																						<xsl:text>&#160; </xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>: </xsl:text>
																					</fo:inline>
																					<fo:inline>
																						<xsl:value-of select="../PACK_ID_LINE_ITEM_BOX_QTY"/>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>: </xsl:text>
																					</fo:inline>
																					<fo:inline>
																						<xsl:value-of select="../PACK_ID_LINE_ITEM_UNIT_QTY"/>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>: </xsl:text>
																					</fo:inline>
																					<fo:inline>
																						<xsl:value-of select="../../PACKID_ACT_WEIGHT"/>
																					</fo:inline>
																					<fo:inline>
																						<xsl:text> KG</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" padding="2pt" display-align="center">
																				<fo:block>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>&#160;</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>&#160;</xsl:text>
																					</fo:inline>
																					<fo:block/>
																					<fo:inline>
																						<xsl:text>&#160;</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text>Box ID</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text> Serial Number</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text>Unit Qty</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
															<xsl:if test="position() mod 3 = 1">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="1pt" border-collapse="collapse" border-color="white" border-style="solid" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_ID">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="center">
																				<fo:block>
																					<xsl:for-each select="SERIAL_NUM">
																						<fo:inline-container>
																							<fo:block>
																								<xsl:text>&#x2029;</xsl:text>
																							</fo:block>
																						</fo:inline-container>
																						<fo:block margin="0pt">
																							<fo:block>
																								<xsl:variable name="value-of-template">
																									<xsl:apply-templates/>
																								</xsl:variable>
																								<xsl:choose>
																									<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																										<fo:block>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:block>
																									</xsl:when>
																									<xsl:otherwise>
																										<fo:inline>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:inline>
																									</xsl:otherwise>
																								</xsl:choose>
																							</fo:block>
																						</fo:block>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_UNIT_QTY">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" number-columns-spanned="3" padding="2pt" display-align="before">
													<fo:block>
														<xsl:for-each select="BOX">
															<xsl:if test="position() mod number(substring($NumBoxPerPage,count(../BOX[1]/SERIAL_NUM)*2-1,2)) = 1">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" height="105pt" number-columns-spanned="3" padding="2pt" text-align="center" display-align="center">
																				<fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin-left="(100% - 100%) div 2" margin-right="(100% - 100%) div 2" margin="0pt">
																						<fo:block>
																							<fo:inline font-size="10pt" font-weight="bold">
																								<xsl:text>BOX ID ATTACHMENT</xsl:text>
																							</fo:inline>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text>Box ID</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text> Serial Number</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text>Unit Qty</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
															<xsl:if test="position() mod 3 = 2">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="1pt" border-collapse="collapse" border-color="white" border-style="solid" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_ID">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="center">
																				<fo:block>
																					<xsl:for-each select="SERIAL_NUM">
																						<fo:inline-container>
																							<fo:block>
																								<xsl:text>&#x2029;</xsl:text>
																							</fo:block>
																						</fo:inline-container>
																						<fo:block margin="0pt">
																							<fo:block>
																								<xsl:variable name="value-of-template">
																									<xsl:apply-templates/>
																								</xsl:variable>
																								<xsl:choose>
																									<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																										<fo:block>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:block>
																									</xsl:when>
																									<xsl:otherwise>
																										<fo:inline>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:inline>
																									</xsl:otherwise>
																								</xsl:choose>
																							</fo:block>
																						</fo:block>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_UNIT_QTY">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" number-columns-spanned="3" padding="2pt" display-align="before">
													<fo:block>
														<xsl:for-each select="BOX">
															<xsl:if test="position() mod number(substring($NumBoxPerPage,count(../BOX[1]/SERIAL_NUM)*2-1,2)) = 1">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" height="105pt" number-columns-spanned="3" padding="2pt" text-align="center" display-align="center">
																				<fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block/>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin-left="(100% - 100%) div 2" margin-right="(100% - 100%) div 2" margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>DATE: </xsl:text>
																							</fo:inline>
																							<xsl:for-each select="$XML">
																								<xsl:for-each select="PACK_ID">
																									<fo:inline>
																										<xsl:value-of select="substring(  CURRENT_DATE  , 1 , $CURRENT_DATE_MAX )"/>
																									</fo:inline>
																								</xsl:for-each>
																							</xsl:for-each>
																							<fo:inline>
																								<xsl:text>&#160; PAGE </xsl:text>
																							</fo:inline>
																							<fo:page-number/>
																							<fo:inline>
																								<xsl:text> of </xsl:text>
																							</fo:inline>
																							<fo:page-number-citation ref-id="SV_RefID_PageTotal"/>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																					<fo:inline-container>
																						<fo:block>
																							<xsl:text>&#x2029;</xsl:text>
																						</fo:block>
																					</fo:inline-container>
																					<fo:block margin="0pt">
																						<fo:block>
																							<fo:inline>
																								<xsl:text>&#160;</xsl:text>
																							</fo:inline>
																						</fo:block>
																					</fo:block>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text> Box ID</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text> Serial Number</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<fo:inline>
																						<xsl:text>Unit Qty</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
															<xsl:if test="position() mod 3 = 0">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="1pt" border-collapse="collapse" border-color="white" border-style="solid" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="40%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-column column-width="30%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_ID">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" display-align="center">
																				<fo:block>
																					<xsl:for-each select="SERIAL_NUM">
																						<fo:inline-container>
																							<fo:block>
																								<xsl:text>&#x2029;</xsl:text>
																							</fo:block>
																						</fo:inline-container>
																						<fo:block margin="0pt">
																							<fo:block>
																								<xsl:variable name="value-of-template">
																									<xsl:apply-templates/>
																								</xsl:variable>
																								<xsl:choose>
																									<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																										<fo:block>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:block>
																									</xsl:when>
																									<xsl:otherwise>
																										<fo:inline>
																											<xsl:copy-of select="$value-of-template"/>
																										</fo:inline>
																									</xsl:otherwise>
																								</xsl:choose>
																							</fo:block>
																						</fo:block>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" line-height="9pt" padding="2pt" text-align="center" display-align="before">
																				<fo:block>
																					<xsl:for-each select="BOX_UNIT_QTY">
																						<xsl:variable name="value-of-template">
																							<xsl:apply-templates/>
																						</xsl:variable>
																						<xsl:choose>
																							<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																								<fo:block>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:block>
																							</xsl:when>
																							<xsl:otherwise>
																								<fo:inline>
																									<xsl:copy-of select="$value-of-template"/>
																								</fo:inline>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<fo:inline>
							<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
						</fo:inline>
						<fo:block/>
						<xsl:if test="string-length(PACK_ID/PACK_ID_LINE_ITEM/PROD_TYPE)&gt;0">
							<fo:inline font-family="@Arial Unicode MS">
								<xsl:text>This order may contain export controlled dual-use commodities, technology, software or services which were supplied in accordance with the US Export Administration Regulations and EU or other national regulations. Diversion contrary to US, EU or other national laws or regulations is prohibited.</xsl:text>
							</fo:inline>
						</xsl:if>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="footerall">
		<fo:static-content flow-name="xsl-region-after">
			<fo:block>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" table-layout="fixed" width="100%">
					<fo:table-column column-width="15%"/>
					<fo:table-column column-width="150"/>
					<fo:table-body start-indent="0pt">
						<fo:table-row>
							<fo:table-cell border="none" font-family="Arial" font-size="7pt" padding="0" height="30" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>WGLAPKA110805</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" font-size="smaller" padding="0" text-align="left" display-align="center">
								<fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block font-family="Arial Black" font-size="7pt" white-space="pre" white-space-collapse="false" margin="0pt">
										<fo:block>
											<xsl:for-each select="$XML">
												<xsl:for-each select="PACK_ID">
													<xsl:for-each select="UDF_HEADER">
														<xsl:if test="./KEY = &apos;ODM_TEXT2&apos; and string-length(./VALUE)&gt;0">
															<fo:inline font-weight="bold">
																<xsl:value-of select="substring( VALUE , 1 , 80 )"/>
															</fo:inline>
														</xsl:if>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</fo:block>
									</fo:block>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row>
							<fo:table-cell border="none" padding="0" number-columns-spanned="2" display-align="center">
								<fo:block>
									<fo:block text-align="center">
										<fo:leader top="-37pt" leader-pattern="rule" rule-thickness="1" leader-length="100%" color="black"/>
									</fo:block>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row>
							<fo:table-cell border="none" font-size="smaller" padding="0" text-align="left" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" font-size="smaller" padding="0" text-align="right" display-align="center">
								<fo:block>
									<fo:inline font-weight="bold">
										<xsl:text>Page: </xsl:text>
									</fo:inline>
									<fo:page-number font-weight="bold"/>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
