USE [HPIMES]
GO

/****** Object:  Index [IDX_PartNo_Desc]    Script Date: 04/05/2014 08:27:25 ******/
CREATE NONCLUSTERED INDEX [IDX_PartNo_Desc] ON [dbo].[Part] 
(
	[PartNo] ASC
)
INCLUDE ( [Remark],
[Flag]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

