USE [master]
GO

/****** Object:  Database [HPIMES_2014]    Script Date: 09/03/2014 10:13:47 ******/
CREATE DATABASE [HPIMES_2014] ON  PRIMARY 
( NAME = N'HPIMES_201406', FILENAME = N'J:\HPIMES_201406\HPIMES_2014.mdf' , SIZE = 5242880KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB ), 
( NAME = N'HPIMES_2014', FILENAME = N'K:\HPIMES_201406\HPIMES_2014_1.ndf' , SIZE = 5242880KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'HPIMES_201406_log', FILENAME = N'I:\HPIMES_201406_LOG\HPIMES_2014_log.ldf' , SIZE = 524288KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [HPIMES_2014] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HPIMES_2014].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HPIMES_2014] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HPIMES_2014] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HPIMES_2014] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HPIMES_2014] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HPIMES_2014] SET ARITHABORT OFF 
GO

ALTER DATABASE [HPIMES_2014] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HPIMES_2014] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HPIMES_2014] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HPIMES_2014] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HPIMES_2014] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HPIMES_2014] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HPIMES_2014] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HPIMES_2014] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HPIMES_2014] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HPIMES_2014] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HPIMES_2014] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HPIMES_2014] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HPIMES_2014] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HPIMES_2014] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HPIMES_2014] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HPIMES_2014] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HPIMES_2014] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HPIMES_2014] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HPIMES_2014] SET  READ_WRITE 
GO

ALTER DATABASE [HPIMES_2014] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HPIMES_2014] SET  MULTI_USER 
GO

ALTER DATABASE [HPIMES_2014] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HPIMES_2014] SET DB_CHAINING OFF 
GO


