<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:param name="ACTUAL_SHIPDATE_max" select="'20'"/>
	<xsl:param name="CUST_ORD_REF_max" select="'25'"/>
	<xsl:param name="INTL_CARRIER_max" select="'20'"/>
	<xsl:param name="ORDER_DATE_max" select="'20'"/>
	<xsl:param name="PO_max" select="'25'"/>
	<xsl:param name="SHIP_TO_CITY_max" select="'27'"/>
	<xsl:param name="SHIP_TO_COUNTRY_NAME_max" select="'30'"/>
	<xsl:param name="SHIP_TO_NAME_2_max" select="'35'"/>
	<xsl:param name="SHIP_TO_NAME_3_max" select="'35'"/>
	<xsl:param name="SHIP_TO_NAME_max" select="'35'"/>
	<xsl:param name="SHIP_TO_STATE_max" select="'3'"/>
	<xsl:param name="SHIP_TO_STREET_2_max" select="'35'"/>
	<xsl:param name="SHIP_TO_STREET_max" select="'35'"/>
	<xsl:param name="SHIP_TO_TELEPHONE_max" select="'20'"/>
	<xsl:param name="SHIP_TO_ZIP_max" select="'10'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="default-page" page-height="11.69in" page-width="8.27in" margin-left="0.6in" margin-right="0.6in">
				<fo:region-body margin-top="6cm" margin-bottom="1.5in"/>
				<fo:region-before extent="6cm"/>
				<fo:region-after extent="1.5in"/>
			</fo:simple-page-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence master-reference="default-page" initial-page-number="1" format="1">
				<xsl:call-template name="headerall"/>
				<xsl:call-template name="footerall"/>
				<fo:flow flow-name="xsl-region-body">
					<fo:block>
						<xsl:for-each select="$XML">
							<fo:block/>
							<xsl:for-each select="PACK_ID">
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x2029;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<xsl:if test="PACK_ID_LINE_ITEM">
									<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-style="normal" font-variant="normal" font-weight="normal" line-height="10pt" padding="0pt" table-layout="fixed" width="100%">
										<fo:table-column column-width="5%"/>
										<fo:table-column column-width="10%"/>
										<fo:table-column column-width="10%"/>
										<fo:table-column column-width="32%"/>
										<fo:table-column column-width="43%"/>
										<fo:table-header start-indent="0pt">
											<fo:table-row background-color="transparent" color="black" line-height="15pt" text-align="center">
												<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" border-right-style="none" border-top="0.5pt" border-top-color="black" border-top-style="solid" padding="0" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" border-left-color="transparent" border-left-style="none" border-top="0.5pt" border-top-color="black" border-top-style="solid" padding="0" display-align="center">
													<fo:block>
														<fo:inline color="black">
															<xsl:text>QTY </xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" border-left-color="transparent" border-left-style="none" border-top="0.5pt" border-top-color="black" border-top-style="solid" padding="0" text-align="left" display-align="center">
													<fo:block>
														<fo:inline color="black">
															<xsl:text>UNIT</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" border-left-color="transparent" border-left-style="none" border-top="0.5pt" border-top-color="black" border-top-style="solid" padding="0" text-align="left" display-align="center">
													<fo:block>
														<fo:inline>
															<xsl:text>ITEM #</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="0.5pt" border-bottom-color="black" border-bottom-style="solid" border-left-color="transparent" border-left-style="none" border-top="0.5pt" border-top-color="black" border-top-style="solid" padding="0" text-align="left" display-align="center">
													<fo:block>
														<fo:inline>
															<xsl:text>ITEM DESCRIPTION</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row background-color="transparent" color="black" line-height="15pt" text-align="center">
												<fo:table-cell border="none" border-right-style="none" number-columns-spanned="5" padding="0" text-align="left" display-align="center">
													<fo:block>
														<fo:inline>
															<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; In this shipment</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-header>
										<fo:table-body start-indent="0pt">
											<xsl:for-each select="PACK_ID_LINE_ITEM">
												<fo:table-row>
													<fo:table-cell border="none" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="0" display-align="before">
														<fo:block/>
													</fo:table-cell>
													<fo:table-cell border="none" border-left-style="none" padding="0" text-align="center" display-align="before">
														<fo:block>
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x2029;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:block margin="0pt">
																<fo:block>
																	<fo:inline>
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:block>
															<xsl:for-each select="PACK_ID_LINE_ITEM_UNIT_QTY">
																<xsl:variable name="value-of-template">
																	<xsl:apply-templates/>
																</xsl:variable>
																<xsl:choose>
																	<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																		<fo:block>
																			<xsl:copy-of select="$value-of-template"/>
																		</fo:block>
																	</xsl:when>
																	<xsl:otherwise>
																		<fo:inline>
																			<xsl:copy-of select="$value-of-template"/>
																		</fo:inline>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:for-each>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-left-style="none" padding="0" text-align="left" display-align="before">
														<fo:block>
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x2029;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:block margin="0pt">
																<fo:block>
																	<fo:inline>
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:block>
															<fo:inline>
																<xsl:text>EA</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-left-style="none" number-columns-spanned="2" padding="0" display-align="before">
														<fo:block>
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x2029;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-style="normal" font-variant="normal" font-weight="normal" padding="0pt" table-layout="fixed" width="100%">
																<fo:table-column column-width="42.5%"/>
																<fo:table-column column-width="57.5%"/>
																<fo:table-body start-indent="0pt">
																	<fo:table-row>
																		<fo:table-cell border="none" border-left-style="none" padding="2pt" display-align="before">
																			<fo:block>
																				<fo:inline-container>
																					<fo:block>
																						<xsl:text>&#x2029;</xsl:text>
																					</fo:block>
																				</fo:inline-container>
																				<fo:block margin="0pt">
																					<fo:block>
																						<fo:inline>
																							<xsl:text>&#160;</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block>
																				<xsl:for-each select="HP_PN">
																					<xsl:variable name="value-of-template">
																						<xsl:apply-templates/>
																					</xsl:variable>
																					<xsl:choose>
																						<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																							<fo:block>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:block>
																						</xsl:when>
																						<xsl:otherwise>
																							<fo:inline>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:inline>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																				<fo:block/>
																				<xsl:for-each select="HP_Cust_PN">
																					<xsl:variable name="value-of-template">
																						<xsl:apply-templates/>
																					</xsl:variable>
																					<xsl:choose>
																						<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																							<fo:block>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:block>
																						</xsl:when>
																						<xsl:otherwise>
																							<fo:inline>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:inline>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</fo:block>
																		</fo:table-cell>
																		<fo:table-cell border="none" border-left-style="none" padding="2pt" display-align="before">
																			<fo:block>
																				<fo:inline-container>
																					<fo:block>
																						<xsl:text>&#x2029;</xsl:text>
																					</fo:block>
																				</fo:inline-container>
																				<fo:block margin="0pt">
																					<fo:block>
																						<fo:inline>
																							<xsl:text>&#160;</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block>
																				<fo:inline-container>
																					<fo:block>
																						<xsl:text>&#x2029;</xsl:text>
																					</fo:block>
																				</fo:inline-container>
																				<fo:block margin="0pt">
																					<fo:block>
																						<xsl:for-each select="PROD_DESC_BASE">
																							<xsl:variable name="value-of-template">
																								<xsl:apply-templates/>
																							</xsl:variable>
																							<xsl:choose>
																								<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																									<fo:block>
																										<xsl:copy-of select="$value-of-template"/>
																									</fo:block>
																								</xsl:when>
																								<xsl:otherwise>
																									<fo:inline>
																										<xsl:copy-of select="$value-of-template"/>
																									</fo:inline>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</fo:block>
																				</fo:block>
																			</fo:block>
																		</fo:table-cell>
																	</fo:table-row>
																</fo:table-body>
															</fo:table>
															<xsl:if test="BOX/SERIAL_NUM != &apos;&apos;">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" padding="0pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="42.5%"/>
																	<fo:table-column column-width="57.5%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" padding="2pt" text-align="right" display-align="before">
																				<fo:block>
																					<fo:inline font-weight="bold">
																						<xsl:text>TRACKING NUMBER:</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" padding="2pt" display-align="center">
																				<fo:block>
																					<xsl:for-each select="BOX">
																						<fo:inline-container>
																							<fo:block>
																								<xsl:text>&#x2029;</xsl:text>
																							</fo:block>
																						</fo:inline-container>
																						<fo:block margin="0pt">
																							<fo:block>
																								<xsl:for-each select="TRACK_NO_PARCEL">
																									<xsl:variable name="value-of-template">
																										<xsl:apply-templates/>
																									</xsl:variable>
																									<xsl:choose>
																										<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																											<fo:block>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:block>
																										</xsl:when>
																										<xsl:otherwise>
																											<fo:inline>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:inline>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:for-each>
																							</fo:block>
																						</fo:block>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
															<xsl:if test="BOX/SERIAL_NUM != &apos;&apos;">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" padding="0pt" table-layout="fixed" width="100%">
																	<fo:table-column column-width="42.5%"/>
																	<fo:table-column column-width="57.5%"/>
																	<fo:table-body start-indent="0pt">
																		<fo:table-row>
																			<fo:table-cell border="none" padding="2pt" text-align="right" display-align="before">
																				<fo:block>
																					<fo:inline font-weight="bold">
																						<xsl:text>SERIAL NUMBER:</xsl:text>
																					</fo:inline>
																				</fo:block>
																			</fo:table-cell>
																			<fo:table-cell border="none" padding="2pt" display-align="center">
																				<fo:block>
																					<xsl:for-each select="BOX">
																						<fo:inline-container>
																							<fo:block>
																								<xsl:text>&#x2029;</xsl:text>
																							</fo:block>
																						</fo:inline-container>
																						<fo:block margin="0pt">
																							<fo:block>
																								<xsl:for-each select="SERIAL_NUM">
																									<fo:inline-container>
																										<fo:block>
																											<xsl:text>&#x2029;</xsl:text>
																										</fo:block>
																									</fo:inline-container>
																									<fo:block margin="0pt">
																										<fo:block>
																											<xsl:variable name="value-of-template">
																												<xsl:apply-templates/>
																											</xsl:variable>
																											<xsl:choose>
																												<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																													<fo:block>
																														<xsl:copy-of select="$value-of-template"/>
																													</fo:block>
																												</xsl:when>
																												<xsl:otherwise>
																													<fo:inline>
																														<xsl:copy-of select="$value-of-template"/>
																													</fo:inline>
																												</xsl:otherwise>
																											</xsl:choose>
																										</fo:block>
																									</fo:block>
																								</xsl:for-each>
																							</fo:block>
																						</fo:block>
																					</xsl:for-each>
																				</fo:block>
																			</fo:table-cell>
																		</fo:table-row>
																	</fo:table-body>
																</fo:table>
															</xsl:if>
															<xsl:if test="count(  .  )  &gt;0">
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:block line-height="5pt" margin="0pt">
																	<fo:block>
																		<fo:inline font-size="8pt">
																			<xsl:text>&#160;</xsl:text>
																		</fo:inline>
																	</fo:block>
																</fo:block>
																<xsl:for-each select="HP_PN_COMPONENTS">
																	<fo:inline-container>
																		<fo:block>
																			<xsl:text>&#x2029;</xsl:text>
																		</fo:block>
																	</fo:inline-container>
																	<fo:block margin="0pt">
																		<fo:block>
																			<fo:inline-container>
																				<fo:block>
																					<xsl:text>&#x2029;</xsl:text>
																				</fo:block>
																			</fo:inline-container>
																			<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-style="normal" font-variant="normal" font-weight="normal" line-height="7pt" padding="0pt" table-layout="fixed" width="100%">
																				<fo:table-column column-width="9%"/>
																				<fo:table-column column-width="22%"/>
																				<fo:table-column column-width="69%"/>
																				<fo:table-body start-indent="0pt">
																					<fo:table-row>
																						<fo:table-cell border="none" padding="2pt" display-align="center">
																							<fo:block>
																								<xsl:for-each select="COMPONENT_UNIT_QTY">
																									<xsl:variable name="value-of-template">
																										<xsl:apply-templates/>
																									</xsl:variable>
																									<xsl:choose>
																										<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																											<fo:block>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:block>
																										</xsl:when>
																										<xsl:otherwise>
																											<fo:inline>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:inline>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:for-each>
																								<fo:inline>
																									<xsl:text> EA</xsl:text>
																								</fo:inline>
																							</fo:block>
																						</fo:table-cell>
																						<fo:table-cell border="none" padding="2pt" display-align="center">
																							<fo:block>
																								<xsl:for-each select="HP_PN_COMPONENT">
																									<xsl:variable name="value-of-template">
																										<xsl:apply-templates/>
																									</xsl:variable>
																									<xsl:choose>
																										<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																											<fo:block>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:block>
																										</xsl:when>
																										<xsl:otherwise>
																											<fo:inline>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:inline>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:for-each>
																							</fo:block>
																						</fo:table-cell>
																						<fo:table-cell border="none" padding="2pt" display-align="center">
																							<fo:block>
																								<xsl:for-each select="PROD_DESC_COMP">
																									<xsl:variable name="value-of-template">
																										<xsl:apply-templates/>
																									</xsl:variable>
																									<xsl:choose>
																										<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																											<fo:block>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:block>
																										</xsl:when>
																										<xsl:otherwise>
																											<fo:inline>
																												<xsl:copy-of select="$value-of-template"/>
																											</fo:inline>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:for-each>
																							</fo:block>
																						</fo:table-cell>
																					</fo:table-row>
																				</fo:table-body>
																			</fo:table>
																		</fo:block>
																	</fo:block>
																</xsl:for-each>
															</xsl:if>
														</fo:block>
													</fo:table-cell>
												</fo:table-row>
											</xsl:for-each>
											<fo:table-row line-height="10pt">
												<fo:table-cell border="none" padding="0" display-align="before">
													<fo:block>
														<fo:inline>
															<xsl:text>&#160;&#160; </xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-left-style="none" padding="0" text-align="center" display-align="before">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-left-style="none" padding="0" text-align="left" display-align="before">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-left-style="none" padding="0" display-align="before">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-left-style="none" padding="0" display-align="before">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
								</xsl:if>
							</xsl:for-each>
						</xsl:for-each>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="headerall">
		<fo:static-content flow-name="xsl-region-before">
			<fo:block>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-style="normal" font-variant="normal" font-weight="normal" padding="0pt" table-layout="fixed" width="100%">
					<fo:table-column column-width="5%"/>
					<fo:table-column column-width="42%"/>
					<fo:table-column column-width="25%"/>
					<fo:table-column column-width="28%"/>
					<fo:table-body start-indent="0pt">
						<fo:table-row>
							<fo:table-cell border="none" font-family="Arial" font-size="12pt" font-style="normal" font-variant="normal" font-weight="bold" padding="2pt" text-align="center" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" font-family="Arial" font-size="12pt" font-style="normal" font-variant="normal" font-weight="bold" padding="2pt" text-align="left" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="left" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" display-align="center">
								<fo:block/>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row line-height="8pt">
							<fo:table-cell border="none" font-family="Arial" font-size="12pt" font-style="normal" font-variant="normal" font-weight="bold" padding="2pt" text-align="center" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>&#160;&#160; </xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" font-family="Arial" font-size="12pt" font-style="normal" font-variant="normal" font-weight="bold" padding="2pt" text-align="left" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="left" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="right" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>PAGE&#160; </xsl:text>
									</fo:inline>
									<fo:page-number/>
									<fo:inline>
										<xsl:text>&#160; of&#160;&#160;&#160;&#160; </xsl:text>
									</fo:inline>
									<fo:page-number-citation ref-id="SV_RefID_PageTotal"/>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row>
							<fo:table-cell border="none" display-align="before" number-columns-spanned="4" padding="2pt" height="20" text-align="center">
								<fo:block>
									<fo:inline font-family="Arial" font-size="16pt" font-weight="bold">
										<xsl:text>CUSTOMER PACKING LIST</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row>
							<fo:table-cell border="none" display-align="before" padding="2pt" height="934">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" display-align="before" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" height="934">
								<fo:block>
									<fo:inline>
										<xsl:text>SHIP TO: </xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  SHIP_TO_NAME  , 1 , $SHIP_TO_NAME_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  SHIP_TO_NAME_2  , 1 , $SHIP_TO_NAME_2_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  SHIP_TO_NAME_3  , 1 , $SHIP_TO_NAME_3_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  SHIP_TO_STREET  , 1 , $SHIP_TO_STREET_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  SHIP_TO_STREET_2  , 1 , $SHIP_TO_STREET_2_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring( SHIP_TO_CITY , 1 , $SHIP_TO_CITY_max )"/>
											</fo:inline>
											<fo:inline>
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
											<xsl:if test="string-length(SHIP_TO_STATE) &gt;0">
												<fo:inline>
													<xsl:value-of select="concat(&quot;, &quot;, substring( SHIP_TO_STATE , 1, $SHIP_TO_STATE_max ))"/>
												</fo:inline>
												<fo:inline>
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</xsl:if>
											<xsl:if test="string-length(SHIP_TO_ZIP) &gt;0">
												<fo:inline>
													<xsl:value-of select="concat(&quot;  &quot;, substring( SHIP_TO_ZIP , 1, $SHIP_TO_ZIP_max ))"/>
												</fo:inline>
											</xsl:if>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring( SHIP_TO_COUNTRY_NAME , 1 , $SHIP_TO_COUNTRY_NAME_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring( SHIP_TO_TELEPHONE , 1 , $SHIP_TO_TELEPHONE_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" display-align="before" padding="2pt" height="934">
								<fo:block>
									<fo:block/>
									<fo:inline>
										<xsl:text>P.O. NUMBER : </xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline>
										<xsl:text>REFERENCE ORDER # : </xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline>
										<xsl:text>ORDER DATE : </xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline>
										<xsl:text>CARRIER : </xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline>
										<xsl:text>SHIP DATE : </xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" display-align="before" padding="2pt" height="934">
								<fo:block>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring( CUST_PO , 1 , $PO_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:inline>
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring( CUST_ORD_REF , 1 , $CUST_ORD_REF_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:inline>
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  ORDER_DATE_HP_PO  , 1 , $ORDER_DATE_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:inline>
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  INTL_CARRIER  , 1 , $INTL_CARRIER_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:inline>
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="$XML">
										<xsl:for-each select="PACK_ID">
											<fo:inline>
												<xsl:value-of select="substring(  ACTUAL_SHIPDATE  , 1 , $ACTUAL_SHIPDATE_max )"/>
											</fo:inline>
										</xsl:for-each>
									</xsl:for-each>
									<fo:inline>
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="footerall">
		<fo:static-content flow-name="xsl-region-after">
			<fo:block>
				<fo:inline>
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</fo:inline>
				<fo:inline font-weight="bold">
					<xsl:text>Please retain this document as proof of purchase</xsl:text>
				</fo:inline>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" border-collapse="collapse" border-style="none" border-top=".5pt" border-top-color="black" border-top-style="solid" font-family="Arial" font-size="8pt" font-style="normal" font-variant="normal" font-weight="normal" padding="0pt" display-align="before" table-layout="fixed" width="100%">
					<fo:table-column column-width="5%"/>
					<fo:table-column column-width="20%"/>
					<fo:table-column column-width="50%"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-body start-indent="0pt">
						<fo:table-row>
							<fo:table-cell border="none" border-style="none" padding="0pt" display-align="before">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="0pt" text-align="left" display-align="before">
								<fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block margin="0pt">
										<fo:block>
											<fo:inline font-weight="bold">
												<xsl:text>TOTAL CARTONS :&#160; </xsl:text>
											</fo:inline>
											<xsl:for-each select="PACK_ID">
												<xsl:for-each select="PACK_ID_BOX_QTY">
													<xsl:variable name="value-of-template">
														<xsl:apply-templates/>
													</xsl:variable>
													<xsl:choose>
														<xsl:when test="contains(string($value-of-template),'&#x2029;')">
															<fo:block font-weight="bold">
																<xsl:copy-of select="$value-of-template"/>
															</fo:block>
														</xsl:when>
														<xsl:otherwise>
															<fo:inline font-weight="bold">
																<xsl:copy-of select="$value-of-template"/>
															</fo:inline>
														</xsl:otherwise>
													</xsl:choose>
												</xsl:for-each>
											</xsl:for-each>
										</fo:block>
									</fo:block>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" border-style="none" padding="0pt" text-align="center" display-align="before">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="None" border-style="none" display-align="before" number-columns-spanned="3" padding="2pt" text-align="center">
								<fo:block>
									<fo:inline font-weight="bold">
										<xsl:text>RETURN TO :</xsl:text>
									</fo:inline>
									<fo:block/>
									<xsl:for-each select="PACK_ID">
										<xsl:for-each select="RESELLER_NAME">
											<xsl:variable name="value-of-template">
												<xsl:apply-templates/>
											</xsl:variable>
											<xsl:choose>
												<xsl:when test="contains(string($value-of-template),'&#x2029;')">
													<fo:block>
														<xsl:copy-of select="$value-of-template"/>
													</fo:block>
												</xsl:when>
												<xsl:otherwise>
													<fo:inline>
														<xsl:copy-of select="$value-of-template"/>
													</fo:inline>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:for-each>
									</xsl:for-each>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" border-collapse="collapse" border-top="0.5pt" border-top-color="black" border-top-style="solid" font-family="Arial" font-size="8pt" padding="0pt" table-layout="fixed" width="100%">
					<fo:table-column column-width="20%"/>
					<fo:table-column column-width="50%"/>
					<fo:table-column column-width="30%"/>
					<fo:table-body start-indent="0pt">
						<fo:table-row>
							<fo:table-cell border="none" font-family="Arial" font-size="7pt" padding="2pt" text-align="left" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>NCRCPKS100412</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="right" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>If you ordered peripheral items, they may arrive separately</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" font-family="Arial" font-size="7pt" padding="2pt" text-align="right" display-align="center">
								<fo:block>
									<fo:inline>
										<xsl:text>Packing List - CUSTOMER COPY</xsl:text>
									</fo:inline>
									<fo:block/>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
						<fo:table-row>
							<fo:table-cell border="none" font-size="smaller" padding="0" number-columns-spanned="3" text-align="left" display-align="center">
								<fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block margin="0pt">
										<fo:block>
											<fo:inline>
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block font-family="Arial Black" font-size="7pt" white-space="pre" white-space-collapse="false" margin="0pt">
										<fo:block>
											<xsl:for-each select="$XML">
												<xsl:for-each select="PACK_ID">
													<xsl:for-each select="UDF_HEADER">
														<xsl:if test="./KEY = &apos;ODM_TEXT2&apos; and string-length(./VALUE)&gt;0">
															<fo:inline font-weight="bold">
																<xsl:value-of select="substring( VALUE , 1 , 80 )"/>
															</fo:inline>
														</xsl:if>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</fo:block>
									</fo:block>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
