<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:param name="CONSOL_INVOICE_max" select="'30'"/>
	<xsl:param name="HP_PN_max" select="'18'"/>
	<xsl:param name="INTL_CARRIER_max" select="'10'"/>
	<xsl:param name="MASTER_WAYBILL_NUMBER_max" select="'30'"/>
	<xsl:param name="Num_LineItem_PerPage" select="'10'"/>
	<xsl:param name="Num_LineItem_Shift" select="'2'"/>
	<xsl:param name="ODM_BARCODE1_max" select="'10'"/>
	<xsl:param name="ODM_TEXT1_max" select="'44'"/>
	<xsl:param name="ODM_TEXT2_max" select="'10'"/>
	<xsl:param name="ODM_TEXT3_max" select="'21'"/>
	<xsl:param name="PACK_ID_max" select="'13'"/>
	<xsl:param name="WAYBILL_NUMBER_max" select="'32'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="default-page" page-height="15.24cm" page-width="10.16cm" margin-left="0.5cm" margin-right="0.5cm">
				<fo:region-body margin-top="0.3cm" margin-bottom="-0.6cm"/>
			</fo:simple-page-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence master-reference="default-page" initial-page-number="1" format="1">
				<fo:flow flow-name="xsl-region-body">
					<fo:block border="none">
						<xsl:for-each select="$XML">
							<xsl:for-each select="PALLETS">
								<xsl:for-each select="PALLET">
									<xsl:if test="position() &gt; 1">
										<fo:block break-after="page">
											<fo:leader leader-pattern="space"/>
										</fo:block>
									</xsl:if>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" border-collapse="collapse" height="10pt" line-height="10pt" margin="0pt" padding="0pt" table-layout="fixed" width="100%">
										<fo:table-column column-width="20%"/>
										<fo:table-column column-width="55%"/>
										<fo:table-column column-width="25%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none" height="8pt" line-height="8pt">
												<fo:table-cell border="none" font-family="Arial" font-size="6pt" padding="2pt" display-align="center">
													<fo:block>
														<fo:external-graphic border="none" content-height="35pt" content-width="35pt">
															<xsl:attribute name="src">
																<xsl:text>url(</xsl:text>
																<xsl:call-template name="double-backslash">
																	<xsl:with-param name="text">
																		<xsl:value-of select="string(&apos;Image_HPLogo_003_20091106.jpg&apos;)"/>
																	</xsl:with-param>
																	<xsl:with-param name="text-length">
																		<xsl:value-of select="string-length(string(&apos;Image_HPLogo_003_20091106.jpg&apos;))"/>
																	</xsl:with-param>
																</xsl:call-template>
																<xsl:text>)</xsl:text>
															</xsl:attribute>
														</fo:external-graphic>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-weight="bold" padding="0pt" display-align="after">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="8pt" font-weight="normal" padding="0pt" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Carrier:</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="Arial" font-size="8pt" font-weight="bold">
															<xsl:value-of select="substring(  INTL_CARRIER  , 1 , $INTL_CARRIER_max )"/>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none" height="12pt">
												<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="9pt" font-weight="bold" padding="0pt" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" number-columns-spanned="3" display-align="after">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Pallet ID : </xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:value-of select="PALLET_ID"/>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none" height="16pt">
												<fo:table-cell border="none" font-family="Free 3 of 9 Extended" font-size="24pt" padding="0pt" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" number-columns-spanned="3" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>*</xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:value-of select="PALLET_ID"/>
														</fo:inline>
														<fo:inline border="none">
															<xsl:text>*</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none" height="18pt">
												<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="9pt" font-weight="bold" padding="0pt" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" number-columns-spanned="3" display-align="after">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>House Waybill # : </xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:value-of select="substring(  WAYBILL_NUMBER  , 1 , $WAYBILL_NUMBER_max )"/>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none" height="16pt">
												<fo:table-cell border="none" font-family="Free 3 of 9 Extended" font-size="24pt" padding="0pt" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" number-columns-spanned="3" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>*</xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:value-of select="WAYBILL_NUMBER"/>
														</fo:inline>
														<fo:inline border="none">
															<xsl:text>*</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" font-size="10pt" height="10pt" line-height="10pt" table-layout="fixed" width="100%" border-spacing="2pt">
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="70%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" font-family="Arial" font-size="7pt" display-align="before" padding="2pt">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>WGOPSLTB130812</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" font-family="Arial" font-size="10pt" font-style="normal" font-variant="normal" font-weight="bold" height="10pt" line-height="10pt" padding="2pt" text-align="right" display-align="center">
													<fo:block>
														<fo:inline border="none" border-bottom="none" border-left="none" font-family="Arial" font-size="10pt">
															<xsl:text>Total Box Qty&#160;&#160;&#160;&#160;&#160; </xsl:text>
														</fo:inline>
														<xsl:for-each select="PALLET_BOX_QTY">
															<xsl:variable name="value-of-template">
																<xsl:apply-templates/>
															</xsl:variable>
															<xsl:choose>
																<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																	<fo:block border="none" font-family="Arial" font-size="10pt" font-weight="bold">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:block>
																</xsl:when>
																<xsl:otherwise>
																	<fo:inline border="none" font-family="Arial" font-size="10pt" font-weight="bold">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:inline>
																</xsl:otherwise>
															</xsl:choose>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<xsl:for-each select="PACK_ID_LINE_ITEM">
										<xsl:choose>
											<xsl:when test="position() = 1 and position()=last()">
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" height="10pt" line-height="10pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="45%"/>
													<fo:table-column column-width="20%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Pack ID</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left-color="black" border-left-style="solid" border-left-width="1pt" border-right="none" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Part Number</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="transparent" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Qty</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="transparent" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
											<xsl:when test="position() = 1">
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" height="10pt" line-height="10pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="42%"/>
													<fo:table-column column-width="23%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Pack ID</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left-color="black" border-left-style="solid" border-left-width="1pt" border-right="none" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Part Number</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Qty</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
											<xsl:when test="(position() + $Num_LineItem_Shift) mod $Num_LineItem_PerPage= 1 and position()=last()">
												<fo:block break-after="page">
													<fo:leader leader-pattern="space"/>
												</fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-size="10pt" height="16pt" line-height="16pt" margin="0pt" padding="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="proportional-column-width(1)"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-weight="bold" height="10pt" line-height="10pt" padding="0pt" display-align="after">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text> Pallet ID :&#160; </xsl:text>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:value-of select="../PALLET_ID"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" font-family="Free 3 of 9 Extended" font-size="18pt" padding="0pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>*</xsl:text>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:value-of select="../PALLET_ID"/>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:text>*</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" height="16pt" line-height="16pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="42%"/>
													<fo:table-column column-width="23%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Pack ID</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left-color="black" border-left-style="solid" border-left-width="1pt" border-right="none" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Part Number</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Qty</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
											<xsl:when test="(position() + $Num_LineItem_Shift) mod $Num_LineItem_PerPage= 1">
												<fo:block break-after="page">
													<fo:leader leader-pattern="space"/>
												</fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-size="10pt" height="16pt" line-height="16pt" margin="0pt" padding="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="proportional-column-width(1)"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" font-weight="bold" height="10pt" line-height="10pt" padding="0pt" display-align="after">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text> Pallet ID :&#160; </xsl:text>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:value-of select="../PALLET_ID"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" font-family="Free 3 of 9 Extended" font-size="18pt" padding="0pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>*</xsl:text>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:value-of select="../PALLET_ID"/>
																	</fo:inline>
																	<fo:inline border="none">
																		<xsl:text>*</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" height="16pt" line-height="16pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="42%"/>
													<fo:table-column column-width="23%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Pack ID</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left-color="black" border-left-style="solid" border-left-width="1pt" border-right="none" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="center" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Part Number</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-bottom-color="black" border-bottom-style="solid" border-bottom-width="1pt" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top-color="black" border-top-style="solid" border-top-width="1pt" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:text>Qty</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
														<fo:table-row border="none">
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
											<xsl:when test="((position() + $Num_LineItem_Shift) mod $Num_LineItem_PerPage = 0) or (position()=last())">
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-collapse="collapse" font-family="Arial" font-size="10pt" height="10pt" line-height="10pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="42%"/>
													<fo:table-column column-width="23%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
											<xsl:when test="position() &gt;0">
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:table border="none" border-collapse="collapse" font-family="Arial" font-size="10pt" height="10pt" line-height="10pt" margin="0pt" table-layout="fixed" width="100%">
													<fo:table-column column-width="35%"/>
													<fo:table-column column-width="42%"/>
													<fo:table-column column-width="23%"/>
													<fo:table-body border="none" start-indent="0pt">
														<fo:table-row border="none">
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  PACK_ID  , 1 , $PACK_ID_max )"/>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" white-space-collapse="true" linefeed-treatment="treat-as-space" wrap-option="no-wrap" white-space-treatment="ignore-if-surrounding-linefeed" padding="2pt" display-align="center">
																<fo:block>
																	<fo:inline border="none">
																		<xsl:value-of select="substring(  HP_PN  , 1 , $HP_PN_max )"/>
																	</fo:inline>
																	<fo:block/>
																	<xsl:for-each select="HP_PN">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																	<fo:inline border="none">
																		<xsl:text>&#160;</xsl:text>
																	</fo:inline>
																</fo:block>
															</fo:table-cell>
															<fo:table-cell border="none" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="right" display-align="center">
																<fo:block>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<fo:block/>
																	<xsl:for-each select="PACK_ID_LINE_ITEM_BOX_QTY_PER_PALLET">
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																		<xsl:variable name="value-of-template">
																			<xsl:apply-templates/>
																		</xsl:variable>
																		<xsl:choose>
																			<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																				<fo:block border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:block>
																			</xsl:when>
																			<xsl:otherwise>
																				<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																					<xsl:copy-of select="$value-of-template"/>
																				</fo:inline>
																			</xsl:otherwise>
																		</xsl:choose>
																		<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																			<xsl:text>*</xsl:text>
																		</fo:inline>
																	</xsl:for-each>
																</fo:block>
															</fo:table-cell>
														</fo:table-row>
													</fo:table-body>
												</fo:table>
											</xsl:when>
										</xsl:choose>
									</xsl:for-each>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 0">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 1">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 2">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 3">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 4">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 5">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 6">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 7">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 8">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 9">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 10">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 11">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 12">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 13">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 14">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 15">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 16">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 17">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 18">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 19">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 20">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 21">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 22">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 23">
										<fo:block/>
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" height="14pt" line-height="14pt" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<xsl:if test="(($Num_LineItem_PerPage - ((count(  PACK_ID_LINE_ITEM)  + $Num_LineItem_Shift ) mod $Num_LineItem_PerPage)) mod $Num_LineItem_PerPage ) &gt; 24">
										<fo:block/>
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:block border="none" margin="0pt">
											<fo:block>
												<fo:inline border="none">
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:block>
									</xsl:if>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" table-layout="fixed" width="100%" border-spacing="2pt">
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" number-columns-spanned="4" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline-container>
															<fo:block>
																<xsl:text>&#x2029;</xsl:text>
															</fo:block>
														</fo:inline-container>
														<fo:block border="none" white-space="pre" white-space-collapse="false" margin="0pt">
															<fo:block>
																<xsl:for-each select="PACK_ID_LINE_ITEM">
																	<xsl:for-each select="UDF_HEADER">
																		<xsl:if test="./KEY = &apos;ODM_TEXT1&apos; and string-length(./VALUE)&gt;0">
																			<fo:inline border="none" font-family="Arial" font-size="12pt" font-weight="bold">
																				<xsl:value-of select="substring( VALUE , 1 , $ODM_TEXT1_max )"/>
																			</fo:inline>
																		</xsl:if>
																	</xsl:for-each>
																</xsl:for-each>
															</fo:block>
														</fo:block>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
