<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:param name="ODM_TEXT1_max" select="'300'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="default-page" page-height="11.69in" page-width="8.27in" margin-left="0.5cm" margin-right="0.5cm">
				<fo:region-body margin-top="3cm" margin-bottom="1cm"/>
				<fo:region-before extent="3cm"/>
				<fo:region-after extent="1cm"/>
			</fo:simple-page-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence master-reference="default-page" initial-page-number="1" format="1">
				<xsl:call-template name="headerall"/>
				<xsl:call-template name="footerall"/>
				<fo:flow flow-name="xsl-region-body">
					<fo:block border="none">
						<xsl:for-each select="$XML">
							<fo:block/>
							<xsl:for-each select="TRUCK">
								<xsl:for-each select="FORWARDER">
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" font-family="Arial" font-size="10pt" table-layout="fixed" width="100%" border-spacing="0">
										<fo:table-column column-width="30%"/>
										<fo:table-column column-width="32%"/>
										<fo:table-column column-width="23%"/>
										<fo:table-column column-width="15%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>ODM Name</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>(工厂名字)</xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:text>:</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="SHIP_FROM_NAME_2">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none" font-family="宋体">
                                        <xsl:copy-of select="$value-of-template"/>
                                      </fo:block>
                                    </xsl:when>
                                    <xsl:otherwise>
                                      <fo:inline border="none" font-family="宋体">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Ship Date(</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>提货日期):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="ACTUAL_SHIPDATE">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Intl. Forwarder</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>(货代名字):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="INTL_CARRIER">
															<xsl:variable name="value-of-template">
																<xsl:apply-templates/>
															</xsl:variable>
															<xsl:choose>
																<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																	<fo:block border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:block>
																</xsl:when>
																<xsl:otherwise>
																	<fo:inline border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:inline>
																</xsl:otherwise>
															</xsl:choose>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Ship Mode(</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>运输方式):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="SHIP_MODE">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Incoterm</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>(运输条款):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="INCOTERM">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Truck ID(</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>卡车号):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" font-family="宋体" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="TRUCK_ID">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Container ID </xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>集装箱号(仅海运):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="CONTAINER_ID">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Seal Number(</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>封号):</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="SEAL_NUMBER">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top="1pt" border-top-color="black" border-top-style="solid" font-family="Arial" font-size="10pt" table-layout="fixed" width="100%" border-spacing="-1pt">
										<fo:table-column column-width="4%"/>
										<fo:table-column column-width="21%"/>
										<fo:table-column column-width="7%"/>
										<fo:table-column column-width="9%"/>
										<fo:table-column column-width="9%"/>
										<fo:table-column column-width="25%"/>
										<fo:table-column column-width="25%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row background-color="#787878" border="none" color="white">
												<fo:table-cell border="none" border-bottom-style="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>No.</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>编号</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Pallet ID</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>托盘号</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Region</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>地区</xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:text>&#160;</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Box Qty</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>箱数</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>G.W. (KG)</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>毛重</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>HAWB# or HWB#</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>分单号 </xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="0" text-align="center" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>MWB#</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>主单号（仅海运)</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<xsl:for-each select="PALLET">
										<fo:inline-container>
											<fo:block>
												<xsl:text>&#x2029;</xsl:text>
											</fo:block>
										</fo:inline-container>
										<fo:table border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top="1pt" border-top-color="black" border-top-style="solid" font-family="Arial" font-size="10pt" table-layout="fixed" width="100%" border-spacing="-1pt">
											<fo:table-column column-width="4%"/>
											<fo:table-column column-width="21%"/>
											<fo:table-column column-width="7%"/>
											<fo:table-column column-width="9%"/>
											<fo:table-column column-width="9%"/>
											<fo:table-column column-width="25%"/>
											<fo:table-column column-width="25%"/>
											<fo:table-body border="none" start-indent="0pt">
												<fo:table-row border="none" line-height="14pt">
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="position()"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="PALLET_ID"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="REGION"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="PALLET_BOX_QTY"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="PALLET_ACT_WEIGHT"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" border-right="1pt" border-right-color="black" border-right-style="solid" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="WAYBILL_NUMBER"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
													<fo:table-cell border="none" padding="2pt" text-align="center" display-align="center">
														<fo:block>
															<fo:inline border="none">
																<xsl:value-of select="MASTER_WAYBILL_NUMBER"/>
															</fo:inline>
														</fo:block>
													</fo:table-cell>
												</fo:table-row>
											</fo:table-body>
										</fo:table>
									</xsl:for-each>
									<fo:block/>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" font-family="Arial" font-size="12pt" font-weight="bold" table-layout="fixed" width="100%" border-spacing="2pt">
										<fo:table-column column-width="35%"/>
										<fo:table-column column-width="30%"/>
										<fo:table-column column-width="30%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Total Pallet</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>总托盘数</xsl:text>
														</fo:inline>
														<fo:inline border="none">
															<xsl:text>:</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="TRUCK_LSP_PALLET_QTY">
															<xsl:variable name="value-of-template">
																<xsl:apply-templates/>
															</xsl:variable>
															<xsl:choose>
																<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																	<fo:block border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:block>
																</xsl:when>
																<xsl:otherwise>
																	<fo:inline border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:inline>
																</xsl:otherwise>
															</xsl:choose>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Total Box</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>总箱数:</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="TRUCK_LSP_BOX_QTY">
															<xsl:variable name="value-of-template">
																<xsl:apply-templates/>
															</xsl:variable>
															<xsl:choose>
																<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																	<fo:block border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:block>
																</xsl:when>
																<xsl:otherwise>
																	<fo:inline border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:inline>
																</xsl:otherwise>
															</xsl:choose>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Total Gross Weight</xsl:text>
														</fo:inline>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>总毛重:</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="TRUCK_LSP_ACT_WEIGHT">
															<xsl:variable name="value-of-template">
																<xsl:apply-templates/>
															</xsl:variable>
															<xsl:choose>
																<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																	<fo:block border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:block>
																</xsl:when>
																<xsl:otherwise>
																	<fo:inline border="none">
																		<xsl:copy-of select="$value-of-template"/>
																	</fo:inline>
																</xsl:otherwise>
															</xsl:choose>
															<fo:inline border="none">
																<xsl:text> KGS</xsl:text>
															</fo:inline>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>1. Did forwarder in-house or its authorized party</xsl:text>
									</fo:inline>
									<fo:inline border="none">
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>witness below activities? </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>货代驻厂或货代委托人是否见证了以下行为,请选择：</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>□ TRUCK LOADING </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>装车 </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160;&#160;&#160; □ CARGO STOWAGE </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>货物固定保护</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; □ TRUCK SEALING </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>加封</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>2.In case forwarder in-house or its authorized party didn’t witness any or all of the mentioned the activities. Please choose reason: </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>如果货代驻厂或货代委托人没有见证上述一项或所有行为, 请选择原因:</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>□ was not allowed by depot </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>仓库不允许</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; □ driver choose not to witness </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>司机自己选择不见证</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>3. Did forwarder in-house or its authorized party find problems from loading? </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>货代驻厂或货代委托人是否在装箱过程中发现异常?</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>□ YES&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; □ NO</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>If yes, please note here problems:</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>如果选择是, 请选择发现的问题:</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>□ visible damage </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>可见的破损 </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160; □ not all pallets are loaded </xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>不是所有货物都已装车</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;&#160;&#160;&#160;&#160; □ other, please list</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt">
										<xsl:text>其他，请列明______________________________</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-family="Arial" font-size="10pt">
										<xsl:text>&#160;</xsl:text>
									</fo:inline>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" font-family="Arial" font-size="10pt" table-layout="fixed" width="100%" border-spacing="2pt">
										<fo:table-column column-width="25%"/>
										<fo:table-column column-width="22%"/>
										<fo:table-column column-width="3%"/>
										<fo:table-column column-width="25%"/>
										<fo:table-column column-width="22%"/>
										<fo:table-column column-width="3%"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>ODM Rep. Name:</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>工厂代表姓名</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" font-family="宋体" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="ODM_REP_NAME">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Forwarder in-house name or its authorized party:</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>货代驻厂或货代委托人姓名</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" font-family="宋体" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="$XML">
															<xsl:for-each select="TRUCK">
																<xsl:for-each select="LSP_REP_NAME">
																	<xsl:variable name="value-of-template">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																			<fo:block border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline border="none">
																				<xsl:copy-of select="$value-of-template"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" font-family="宋体" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>ODM Rep. signiture: </xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>工厂代表签字</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Forwarder in-houseor its authorized party signiture: </xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>货代驻厂或货代委托人签字</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row border="none">
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Date and Time:</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>日期时间</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>Date and Time:</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline border="none" font-family="宋体">
															<xsl:text>日期时间</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
												<fo:table-cell border="none" border-bottom-style="none" padding="2pt" display-align="center">
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline border="none" font-family="Arial" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>ODM Remark</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>工厂备注</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>:</xsl:text>
									</fo:inline>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" line-height="60pt" table-layout="fixed" width="100%" border-spacing="-1pt">
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top="1pt" border-top-color="black" border-top-style="solid" line-height="15pt" padding="2pt" display-align="center">
													<fo:block>
														<xsl:for-each select="UDF_HEADER">
															<xsl:if test="./KEY = &apos;ODM_TEXT1&apos; and string-length(./VALUE)&gt;0">
																<fo:inline border="none" font-family="Arial" font-size="10pt">
																	<xsl:value-of select="substring( VALUE , 1 , $ODM_TEXT1_max )"/>
																</fo:inline>
															</xsl:if>
														</xsl:for-each>
														<fo:inline border="none">
															<xsl:text>&#160;&#160; </xsl:text>
														</fo:inline>
														<xsl:for-each select="UDF_HEADER">
															<xsl:if test="./KEY = &apos;ODM_TEXT1&apos; and string-length(./VALUE)&gt;0">
																<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																	<xsl:text>*</xsl:text>
																</fo:inline>
																<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																	<xsl:value-of select="substring( VALUE , 1 , $ODM_TEXT1_max )"/>
																</fo:inline>
																<fo:inline border="none" font-family="Free 3 of 9 Extended" font-size="18pt">
																	<xsl:text>*</xsl:text>
																</fo:inline>
															</xsl:if>
														</xsl:for-each>
														<fo:inline border="none" font-size="18pt">
															<xsl:text>&#160;&#160; </xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline border="none" font-family="Arial" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>LSP Remark</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="宋体" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>货代备注</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-family="Arial" font-size="10pt" font-weight="bold" text-decoration="underline">
										<xsl:text>:</xsl:text>
									</fo:inline>
									<fo:inline border="none" font-weight="bold" text-decoration="underline">
										<xsl:text></xsl:text>
									</fo:inline>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:table border="none" height="60pt" line-height="60pt" table-layout="fixed" width="100%" border-spacing="-1pt">
										<fo:table-column column-width="proportional-column-width(1)"/>
										<fo:table-body border="none" start-indent="0pt">
											<fo:table-row border="none">
												<fo:table-cell border="none" border-bottom="1pt" border-bottom-color="black" border-bottom-style="solid" border-left="1pt" border-left-color="black" border-left-style="solid" border-right="1pt" border-right-color="black" border-right-style="solid" border-top="1pt" border-top-color="black" border-top-style="solid" line-height="20pt" padding="2pt" display-align="center">
													<fo:block>
														<fo:inline border="none">
															<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
														</fo:inline>
													</fo:block>
												</fo:table-cell>
											</fo:table-row>
										</fo:table-body>
									</fo:table>
									<fo:block/>
									<xsl:if test="position()!=last()">
										<fo:block break-after="page">
											<fo:leader leader-pattern="space"/>
										</fo:block>
									</xsl:if>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="headerall">
		<fo:static-content flow-name="xsl-region-before">
			<fo:block>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" table-layout="fixed" width="100%" border-spacing="2pt">
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-body border="none" start-indent="0pt">
						<fo:table-row border="none">
							<fo:table-cell border="none" border-bottom="1.5pt" border-bottom-color="black" border-bottom-style="solid" font-family="宋体" number-columns-spanned="2" padding="2pt" text-align="center" display-align="center">
								<fo:block>
									<fo:block/>
									<fo:inline-container>
										<fo:block>
											<xsl:text>&#x2029;</xsl:text>
										</fo:block>
									</fo:inline-container>
									<fo:block border="none" margin="0pt">
										<fo:block>
											<fo:inline border="none">
												<xsl:text>&#160;</xsl:text>
											</fo:inline>
										</fo:block>
									</fo:block>
									<fo:inline border="none" font-family="Arial" font-size="20pt" font-weight="bold">
										<xsl:text>POS (Proof of Shipment)</xsl:text>
									</fo:inline>
									<fo:block/>
									<fo:inline border="none" font-size="20pt" font-weight="bold">
										<xsl:text>交接单</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="footerall">
		<fo:static-content flow-name="xsl-region-after">
			<fo:block>
				<fo:inline-container>
					<fo:block>
						<xsl:text>&#x2029;</xsl:text>
					</fo:block>
				</fo:inline-container>
				<fo:table border="none" table-layout="fixed" width="100%" border-spacing="2pt">
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-column column-width="proportional-column-width(1)"/>
					<fo:table-body border="none" start-indent="0pt">
						<fo:table-row border="none">
							<fo:table-cell border="none" padding="2pt" text-align="left" display-align="center">
								<fo:block>
									<fo:inline border="none" font-size="8pt">
										<xsl:text>POS140310</xsl:text>
									</fo:inline>
								</fo:block>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="right" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="right" display-align="center">
								<fo:block/>
							</fo:table-cell>
							<fo:table-cell border="none" padding="2pt" text-align="right" display-align="center">
								<fo:block>
									<fo:page-number border="none" font-family="Arial" font-size="8pt"/>
									<fo:inline border="none" font-family="Arial" font-size="8pt">
										<xsl:text> of </xsl:text>
									</fo:inline>
									<fo:page-number-citation ref-id="SV_RefID_PageTotal" border="none" font-family="Arial" font-size="8pt"/>
								</fo:block>
							</fo:table-cell>
						</fo:table-row>
					</fo:table-body>
				</fo:table>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
