USE [HPIMES]
GO

/****** Object:  Index [IDX_Component]    Script Date: 04/05/2014 08:23:40 ******/
CREATE NONCLUSTERED INDEX [IDX_Component] ON [dbo].[ModelBOM] 
(
	[Component] ASC
)
INCLUDE ( [Material],
[Quantity]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

