USE [HPIMES]
GO

/****** Object:  Index [IX_PartInfo_InfoValue]    Script Date: 04/05/2014 08:29:02 ******/
CREATE NONCLUSTERED INDEX [IX_PartInfo_InfoValue] ON [dbo].[PartInfo] 
(
	[InfoType] ASC,
	[InfoValue] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

