					   
CREATE NONCLUSTERED INDEX [IDX_Code_KittingType] ON [WipBuffer] 
(
	[Code] ASC,
	[KittingType] ASC
)
INCLUDE ( [ID],
[PartNo],
[Tp],
[LightNo],
[Picture],
[Qty],
[Sub],
[Safety_Stock],
[Max_Stock],
[Remark],
[Editor],
[Cdt],
[Udt],
[Station],
[Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Code_PartNo] ON [WipBuffer] 
(
	[Code] ASC,
	[PartNo] ASC
)
INCLUDE ( [ID],
[Tp],
[LightNo],
[Picture],
[Qty],
[Sub],
[Safety_Stock],
[Max_Stock],
[Remark],
[Editor],
[Cdt],
[Udt],
[KittingType],
[Station],
[Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Line] ON [WipBuffer] 
(
	[Line] ASC
)
INCLUDE ( [Code],
[PartNo],
[LightNo],
[Sub]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_WipBuffer_Sub] ON [WipBuffer] 
(
	[Sub] ASC
)
INCLUDE ( [ID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_WipBuffer_Code] ON [WipBuffer] 
(
	[Code] ASC
)
INCLUDE ( [ID],
[PartNo],
[Tp],
[LightNo],
[Picture],
[Qty],
[Sub],
[Safety_Stock],
[Max_Stock],
[Remark],
[Editor],
[Cdt],
[Udt],
[KittingType],
[Station],
[Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_WipBuffer_KittingType] ON [WipBuffer] 
(
	[KittingType] ASC,
	[PartNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_WipBuffer_PartNo] ON [WipBuffer] 
(
	[PartNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_WipBuffer_Tp] ON [WipBuffer] 
(
	[Tp] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [Idx_WH_PLTMas_PLT] ON [WH_PLTMas] 
(
	[PLT] ASC
)
INCLUDE ( [WC]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IX_WH_PLTLog] ON [WH_PLTLog] 
(
	[PLT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_UnpackProduct_CUSTSN] ON [UnpackProduct] 
(
	[CUSTSN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_TxnDataLog_TxnId] ON [TxnDataLog] 
(
	[TxnId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]

CREATE NONCLUSTERED INDEX [IX_TransferToIMESList_PCBNo] ON [TransferToIMESList] 
(
	[PCBNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_RePrintLog_BegNo] ON [RePrintLog] 
(
	[BegNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
GO
CREATE NONCLUSTERED INDEX [IDX_RePrintLog_Descr] ON [RePrintLog] 
(
	[Descr] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
GO
CREATE NONCLUSTERED INDEX [IDX_RePrintLog_EndNo] ON [RePrintLog] 
(
	[EndNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
GO

CREATE NONCLUSTERED INDEX [IDX_DN_GUID] ON [QueryWIP] 
(
	[DN] ASC,
	[GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_QueryWIP] ON [QueryWIP] 
(
	[GUID] ASC,
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_QTime_Line] ON [QTime] 
(
	[Line] ASC
)
INCLUDE ( [Category],
[TimeOut],
[StopTime],
[DefectCode],
[HoldStation],
[HoldStatus],
[ExceptStation],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [<QCStatus_Tp_Line_Cdt>] ON [QCStatus] 
(
	[Tp] ASC,
	[Line] ASC,
	[Cdt] ASC
)
INCLUDE ( [ProductID],
[Model]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_QCStatus_Line_Model_Tp] ON [QCStatus] 
(
	[Tp] ASC,
	[Model] ASC,
	[Line] ASC,
	[Cdt] ASC
)
INCLUDE ( [ProductID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_QCStatus_ModelTp] ON [QCStatus] 
(
	[Tp] ASC,
	[Model] ASC,
	[Cdt] ASC
)
INCLUDE ( [ProductID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_QCStatus_ProductID] ON [QCStatus] 
(
	[ProductID] ASC,
	[Status] ASC
)
INCLUDE ( [ID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_QCStatus_Tp] ON [QCStatus] 
(
	[Tp] ASC,
	[ProductID] ASC
)
INCLUDE ( [Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Ix_QCStatus_LineTP] ON [QCStatus] 
(
	[Tp] ASC,
	[Status] ASC
)
INCLUDE ( [ProductID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IX_ShipDate_PdLine_Model] ON [ProductPlan] 
(
	[PdLine] ASC,
	[ShipDate] ASC,
	[Model] ASC
)
INCLUDE ( [PlanQty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_RunInControl_Code] ON [RunInTimeControl] 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_RunInTimeControl_CodeTestType] ON [RunInTimeControl] 
(
	[Code] ASC,
	[Type] ASC,
	[TestStation] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_RunInTimeControl_Type] ON [RunInTimeControl] 
(
	[Type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_Pallet_UCC] ON [Pallet] 
(
	[UCC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_Station] ON [Pallet] 
(
	[Station] ASC
)
INCLUDE ( [Weight],
[Length],
[Width],
[Height]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO


GO
CREATE NONCLUSTERED INDEX [IDX_BomNodeType_Descr] ON [Part] 
(
	[BomNodeType] ASC,
	[Descr] ASC
)
INCLUDE ( [PartNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Descr] ON [Part] 
(
	[Descr] ASC
)
INCLUDE ( [PartNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PartNo_Desc] ON [Part] 
(
	[PartNo] ASC
)
INCLUDE ( [Remark],
[Flag]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Part_BomNodeType_Flag] ON [Part] 
(
	[BomNodeType] ASC,
	[Flag] ASC
)
INCLUDE ( [Descr],
[PartNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_Part_PartType] ON [Part] 
(
	[PartType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_BomNode_PartType] ON [Part] 
(
	[PartNo] ASC,
	[BomNodeType] ASC,
	[PartType] ASC
)
INCLUDE ( [Descr],
[Remark],
[Flag]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ShipWay_RegId_FullQty] ON [PalletType] 
(
	[ShipWay] ASC,
	[RegId] ASC,
	[StdPltFullQty] ASC,
	[MinQty] ASC,
	[MaxQty] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IX_PalletNo] ON [PalletLog] 
(
	[PalletNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



CREATE NONCLUSTERED INDEX [IDX_PartInfoType] ON [PartInfo] 
(
	[InfoType] ASC
)
INCLUDE ( [PartNo],
[InfoValue],
[ID],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PartNo] ON [PartInfo] 
(
	[PartNo] ASC
)
INCLUDE ( [InfoType],
[InfoValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PartInfo_InfoValue] ON [PartInfo] 
(
	[InfoType] ASC,
	[InfoValue] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Indx_PartNo_InfoType] ON [PartInfo] 
(
	[PartNo] ASC,
	[InfoType] ASC
)
INCLUDE ( [InfoValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



CREATE NONCLUSTERED INDEX [IDX_PizzaLog_PizzaID] ON [PizzaLog] 
(
	[PizzaID] ASC
)
INCLUDE ( [Model],
[Station],
[Line],
[Descr],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_Pizza_CartonSN] ON [Pizza] 
(
	[CartonSN] ASC
)
INCLUDE ( [MMIID],
[Model],
[Cdt],
[Remark]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO




CREATE NONCLUSTERED INDEX [IDX_PrintLog_BegNoName] ON [PrintLog] 
(
	[BegNo] ASC,
	[EndNo] ASC,
	[Name] ASC
)
INCLUDE ( [ID],
[Descr],
[Editor],
[Cdt],
[LabelTemplate],
[Station]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
ALTER INDEX [IDX_PrintLog_BegNoName] ON [dbo].[PrintLog] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_PrintLog_Descr] ON [PrintLog] 
(
	[Name] ASC,
	[Descr] ASC
)
INCLUDE ( [BegNo],
[EndNo],
[Editor],
[Cdt],
[LabelTemplate],
[Station]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
ALTER INDEX [IDX_PrintLog_Descr] ON [dbo].[PrintLog] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_PrintLog_EndNo] ON [PrintLog] 
(
	[EndNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [History]
ALTER INDEX [IDX_PrintLog_EndNo] ON [dbo].[PrintLog] DISABLE
GO
CREATE NONCLUSTERED INDEX [IX_PrintLog_BegNo] ON [PrintLog] 
(
	[BegNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
ALTER INDEX [IX_PrintLog_BegNo] ON [dbo].[PrintLog] DISABLE
GO

CREATE NONCLUSTERED INDEX [IX_PoData_EDI_DeliveryNo] ON [PoData_EDI] 
(
	[DeliveryNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PoData_EDI_Model] ON [PoData_EDI] 
(
	[Model] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

GO
CREATE NONCLUSTERED INDEX [IDX_Product_MAC] ON [Product] 
(
	[MAC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_MO] ON [Product] 
(
	[MO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Product_CartonSN] ON [Product] 
(
	[CartonSN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_DeliveryNo] ON [Product] 
(
	[DeliveryNo] ASC
)
INCLUDE ( [Model],
[PCBID],
[PCBModel],
[MAC],
[UUID],
[MBECR],
[CVSN],
[CUSTSN],
[ECR],
[PizzaID],
[MO],
[UnitWeight],
[CartonSN],
[CartonWeight],
[PalletNo],
[State],
[OOAID],
[PRSN],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_Model] ON [Product] 
(
	[Model] ASC
)
INCLUDE ( [ProductID],
[CUSTSN]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_PCBID] ON [Product] 
(
	[PCBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_PalletNo] ON [Product] 
(
	[PalletNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_PizzaID] ON [Product] 
(
	[PizzaID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [_IDX_CUSTSN] ON [Product] 
(
	[CUSTSN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IX_ProductID] ON [ProductBT] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



CREATE NONCLUSTERED INDEX [IX_Special_Det_SnoId] ON [Special_Det] 
(
	[SnoId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IX_SpecialOrder_Category_Status_Cdt] ON [SpecialOrder] 
(
	[Category] ASC,
	[Status] ASC,
	[Cdt] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



GO
CREATE NONCLUSTERED INDEX [IX_BTBoc_ProdcutID] ON [SnoDet_BTLoc] 
(
	[SnoId] ASC
)
INCLUDE ( [Sno],
[Status]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_BTLoc_Sno] ON [SnoDet_BTLoc] 
(
	[Sno] ASC,
	[Status] ASC
)
INCLUDE ( [SnoId]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO


CREATE NONCLUSTERED INDEX [IDX_SnoCtrlBoxIdSq_Cust] ON [SnoCtrl_BoxId_SQ] 
(
	[Cust] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

 

CREATE NONCLUSTERED INDEX [IX_ShipBoxDet_DeliveryNoSnoIdPLT] ON [ShipBoxDet] 
(
	[DeliveryNo] ASC,
	[SnoId] ASC,
	[PLT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ShipBoxDet_SnoId] ON [ShipBoxDet] 
(
	[SnoId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO


CREATE NONCLUSTERED INDEX [IDX_SendData_Cdt] ON [SendData] 
(
	[Cdt] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Indx_SendData_Txn] ON [SendData] 
(
	[TxnId] ASC,
	[Action] ASC,
	[KeyValue1] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



	
	 






 
	

CREATE NONCLUSTERED INDEX [IDX_OSWIN_Family] ON [HPIMES_OSWIN] 
(
	[Family] ASC
)
INCLUDE ( [Zmode],
[OS],
[AV],
[Image],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_OSWIN_Family_AV] ON [HPIMES_OSWIN] 
(
	[Family] ASC,
	[AV] ASC
)
INCLUDE ( [Zmode],
[OS],
[Image],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



CREATE NONCLUSTERED INDEX [IDX_FwdPlt_Plt_Status] ON [FwdPlt] 
(
	[Plt] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_FwdPlt_PickID] ON [FwdPlt] 
(
	[PickID] ASC
)
INCLUDE ( [Plt],
[Qty],
[Status],
[Date],
[Operator],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

	

CREATE NONCLUSTERED INDEX [Idx_Forwarder_Cdt] ON [Forwarder] 
(
	[Cdt] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IX_ForceNWC_ProductID] ON [ForceNWC] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO





CREATE NONCLUSTERED INDEX [IX_Date_PdLine] ON [FailKPCollection] 
(
	[Date] ASC,
	[PdLine] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_FRUMBVer_PartNo_MBCode] ON [FRUMBVer] 
(
	[PartNo] ASC,
	[MBCode] ASC
)
INCLUDE ( [Ver],
[Remark],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [Idx_FISToSapWeight_Shipment] ON [FISTOSAP_WEIGHT] 
(
	[DN/Shipment] ASC
)
INCLUDE ( [Status],
[KG],
[Cdt],
[SendStatus]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO




CREATE NONCLUSTERED INDEX [IX_FAKittingBoxSN_SnoId] ON [FAKittingBoxSN] 
(
	[SnoId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_EcrVersion] ON [EcrVersion] 
(
	[MBCode] ASC
)
INCLUDE ( [Family],
[ECR],
[IECVer],
[Remark],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_EcrVersion_ECR] ON [EcrVersion] 
(
	[ECR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_EcrVersion_Family] ON [EcrVersion] 
(
	[Family] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [EPIACheckStartTime_Model_VC] ON [EPIACheckStartTime] 
(
	[Model] ASC,
	[VC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO




CREATE NONCLUSTERED INDEX [IX_DescType_Code] ON [DescType] 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO








CREATE NONCLUSTERED INDEX [IDX_DeliveryAttr_DeliveryNo] ON [DeliveryAttr] 
(
	[DeliveryNo] ASC
)
INCLUDE ( [AttrName],
[AttrValue],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_CartonInfo_InfoType_InfoValue] ON [CartonInfo] 
(
	[InfoType] ASC,
	[InfoValue] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CartonInfo_CartonNo] ON [CartonInfo] 
(
	[CartonNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_CacheUpdate_IP_AppName] ON [CacheUpdate] 
(
	[CacheServerIP] ASC,
	[AppName] ASC
)
INCLUDE ( [ID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CacheUpdate_Item] ON [CacheUpdate] 
(
	[Item] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_Updated_IP_AppName] ON [CacheUpdate] 
(
	[Updated] ASC,
	[CacheServerIP] ASC,
	[AppName] ASC,
	[Type] ASC
)
INCLUDE ( [ID],
[Item],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO


CREATE NONCLUSTERED INDEX [IX_CTOBom_MPno] ON [CTOBom] 
(
	[MPno] ASC,
	[SPno] ASC
)
INCLUDE ( [Tp],
[Qty],
[Descr]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_CTOBom_SPno] ON [CTOBom] 
(
	[SPno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO




CREATE NONCLUSTERED INDEX [<COAStatus_Status>] ON [COAStatus] 
(
	[Status] ASC
)
INCLUDE ( [IECPN]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PN_Status_Line] ON [COAStatus] 
(
	[IECPN] ASC,
	[Status] ASC,
	[Line] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO





	
	
CREATE NONCLUSTERED INDEX [IX_Bom_Code_part_number] ON [Bom_Code] 
(
	[part_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO







CREATE NONCLUSTERED INDEX [IDX_Asset_Code_Status] ON [AssetRange] 
(
	[Code] ASC,
	[Status] ASC
)
INCLUDE ( [Begin],
[End]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_AssemblyVC_VC_CombineVC] ON [AssemblyVC] 
(
	[VC] ASC,
	[CombineVC] ASC
)
INCLUDE ( [Family],
[PartNo],
[CombinePartNo],
[Remark],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO





CREATE NONCLUSTERED INDEX [IDX_CheckTypeRule_Type_Line_Station_Family] ON [CheckItemTypeRule] 
(
	[CheckItemType] ASC,
	[Line] ASC,
	[Station] ASC,
	[Family] ASC
)
INCLUDE ( [BomNodeType],
[PartDescr],
[PartType],
[MatchRule],
[CheckRule],
[SaveRule],
[Descr],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE NONCLUSTERED INDEX [IDX_DefectHoldRule_CheckInStation] ON [DefectHoldRule] 
(
	[CheckInStation] ASC
)
INCLUDE ( [Line],
[Family],
[DefectCode],
[EqualSameDefectCount],
[OverDefectCount],
[ExceptCause],
[HoldStation],
[HoldCode],
[HoldDescr],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Pre_Cur_Major_Cause_Defect] ON [DefectCode_Station] 
(
	[PRE_STN] ASC,
	[CRT_STN] ASC,
	[MajorPart] ASC,
	[Cause] ASC,
	[Defect] ASC
)
INCLUDE ( [NXT_STN]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO



CREATE NONCLUSTERED INDEX [IX_MTA_Mark_Rep_Id] ON [MTA_Mark] 
(
	[Rep_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_BTLocMas_SnoId] ON [PAK_BTLocMas] 
(
	[SnoId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_HPPN] ON [OlymBattery] 
(
	[HPPN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NumControl_NoType] ON [NumControl] 
(
	[NoType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NumControl_NoType_Value_Customer] ON [NumControl] 
(
	[NoType] ASC,
	[NoName] ASC,
	[Value] ASC,
	[Customer] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [NoNameNoTypeIndex] ON [NumControl] 
(
	[NoType] ASC,
	[NoName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_Model_Line] ON [Model_Process_TMP] 
(
	[Model] ASC,
	[Line] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLot_LotNo] ON [PCBLot] 
(
	[LotNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLot_PCBNo] ON [PCBLot] 
(
	[PCBNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLog_PCBNo] ON [PCBLog] 
(
	[PCBNo] ASC
)
INCLUDE ( [PCBModel],
[Station],
[Status],
[Line],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLog_Station] ON [PCBLog] 
(
	[PCBNo] ASC,
	[Station] ASC
)
INCLUDE ( [ID],
[PCBModel],
[Status],
[Line],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLog_Status] ON [PCBLog] 
(
	[Status] ASC
)
INCLUDE ( [ID],
[PCBNo],
[PCBModel],
[Station],
[Line],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PCBLog_UnionLineStation] ON [PCBLog] 
(
	[Line] ASC,
	[Station] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PCBInfo_PCBNo_InfoType] ON [PCBInfo] 
(
	[PCBNo] ASC,
	[InfoType] ASC
)
INCLUDE ( [InfoValue],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBInfo_InfoValue] ON [PCBInfo] 
(
	[InfoValue] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBInfo_PCBNo] ON [PCBInfo] 
(
	[PCBNo] ASC
)
INCLUDE ( [ID],
[InfoType],
[InfoValue],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PartInfo_InfoType] ON [PCBInfo] 
(
	[InfoType] ASC
)
INCLUDE ( [ID],
[PCBNo],
[InfoValue],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_ModelWeight_SendStatus] ON [ModelWeight] 
(
	[SendStatus] ASC
)
INCLUDE ( [Model],
[UnitWeight],
[CartonWeight]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_ModelInfo_Name] ON [ModelInfo] 
(
	[Name] ASC
)
INCLUDE ( [Model],
[Value],
[Descr],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_ModelInfo_Model_Name] ON [ModelInfo] 
(
	[Model] ASC,
	[Name] ASC
)
INCLUDE ( [Value],
[Descr]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_ModelChangeQty_Line_Model_Status] ON [ModelChangeQty] 
(
	[Line] ASC,
	[Model] ASC,
	[Status] ASC
)
INCLUDE ( [Qty],
[ShipDate],
[AssignedQty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Component] ON [ModelBOM] 
(
	[Component] ASC
)
INCLUDE ( [Material],
[Quantity]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Material] ON [ModelBOM] 
(
	[Material] ASC
)
INCLUDE ( [Component],
[Quantity],
[Alternative_item_group],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Indx_Material_Component] ON [ModelBOM] 
(
	[Material] ASC,
	[Component] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Model_Family] ON [Model] 
(
	[Family] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Model_ModelStatus] ON [Model] 
(
	[Model] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [<PCBTestLogBack_Station_Status_Cdt>] ON [PCBTestLogBack] 
(
	[Station] ASC,
	[Status] ASC,
	[Cdt] ASC
)
INCLUDE ( [ID],
[PCBNo],
[Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_Cdt] ON [PCBTestLog] 
(
	[PCBNo] ASC,
	[Cdt] ASC
)
INCLUDE ( [ActionName],
[Type],
[Line],
[FixtureID],
[Station],
[Status],
[JoinID],
[Editor],
[ErrorCode],
[Descr],
[Remark]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PCBTestLog_Status_Remark] ON [PCBTestLog] 
(
	[Status] ASC,
	[Remark] ASC
)
INCLUDE ( [Type],
[Line],
[Station],
[Editor],
[Cdt],
[PCBNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBTestLog_PCBNo] ON [PCBTestLog] 
(
	[PCBNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBTestLog_Station] ON [PCBTestLog] 
(
	[Station] ASC
)
INCLUDE ( [PCBNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PCBStatus_Station] ON [PCBStatus] 
(
	[Station] ASC
)
INCLUDE ( [PCBNo],
[Status],
[Line],
[TestFailCount],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_StopLog_Start_End] ON [LineStationStopPeriodLog] 
(
	[Line] ASC,
	[Station] ASC,
	[StartTime] ASC,
	[EndTime] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_MOStatusLog_MO] ON [MOStatusLog] 
(
	[MO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_MO_Model] ON [MO] 
(
	[Model] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_MO_Model_Status] ON [MO] 
(
	[Model] ASC,
	[Status] ASC
)
INCLUDE ( [CreateDate],
[Qty],
[Print_Qty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Status] ON [MO] 
(
	[Status] ASC
)
INCLUDE ( [Qty],
[Print_Qty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_MAWB_Delivery] ON [MAWB] 
(
	[Delivery] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_MAWB_MAWB] ON [MAWB] 
(
	[MAWB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [CodeIndex] ON [MACRange] 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CodeStatusIndex] ON [MACRange] 
(
	[Code] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_Lot_Line_Type] ON [LotSetting] 
(
	[Line] ASC,
	[Type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Kitting_Location_FV_TagID] ON [Kitting_Location_FV] 
(
	[TagID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_KittingLocPLMappingST_UnionLPS] ON [Kitting_Loc_PLMapping_St] 
(
	[LightNo] ASC,
	[PdLine] ASC,
	[Station] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Family_PdLine] ON [KitLoc] 
(
	[Family] ASC,
	[PdLine] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_HoldRule_CheckInStation] ON [HoldRule] 
(
	[CheckInStation] ASC
)
INCLUDE ( [Line],
[Family],
[Model],
[CUSTSN],
[HoldStation],
[HoldCode],
[HoldDescr]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Line_Station_UnionLineStation] ON [Line_Station] 
(
	[Line] ASC,
	[Station] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_TestLog_DefectInfo_PCBTestLogID] ON [PCBTestLog_DefectInfo] 
(
	[PCBTestLogID] ASC
)
INCLUDE ( [DefectCodeID],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
ALTER INDEX [IDX_TestLog_DefectInfo_PCBTestLogID] ON [dbo].[PCBTestLog_DefectInfo] DISABLE
GO
CREATE NONCLUSTERED INDEX [<PCBTestLogBack_DefectInfo_PCBTestLogBackID>] ON [PCBTestLogBack_DefectInfo] 
(
	[PCBTestLogBackID] ASC
)
INCLUDE ( [DefectCodeID],
[TriggerAlarm]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [<PCBTestLogBack_DefectInfo_TriggerAlarm>] ON [PCBTestLogBack_DefectInfo] 
(
	[TriggerAlarm] ASC
)
INCLUDE ( [PCBTestLogBackID],
[DefectCodeID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PCB_CVSN] ON [PCB] 
(
	[CVSN] ASC
)
INCLUDE ( [PCBNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PCB_DeliveryNo] ON [PCB] 
(
	[DeliveryNo] ASC
)
INCLUDE ( [ShipMode],
[CartonSN],
[PalletNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCB_CUSTSN_MAC] ON [PCB] 
(
	[CUSTSN] ASC,
	[MAC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PCB_MAC] ON [PCB] 
(
	[MAC] ASC
)
INCLUDE ( [CUSTSN],
[UUID],
[ECR],
[IECVER],
[CUSTVER],
[SMTMO],
[PCBModelID],
[DateCode],
[CVSN],
[State],
[ShipMode],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCB_SMTMO] ON [PCB] 
(
	[SMTMO] ASC
)
INCLUDE ( [PCBNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCB_ShipMode] ON [PCB] 
(
	[ShipMode] ASC
)
INCLUDE ( [PCBNo],
[CUSTSN],
[MAC],
[UUID],
[ECR],
[IECVER],
[CUSTVER],
[SMTMO],
[PCBModelID],
[DateCode],
[CVSN],
[State],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_Model_Line] ON [Model_Process] 
(
	[Model] ASC,
	[Line] ASC
)
INCLUDE ( [ID],
[Process],
[Editor],
[Cdt],
[Udt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_Model_Status] ON [Delivery] 
(
	[Model] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Delivery_ShipmentNo] ON [Delivery] 
(
	[ShipmentNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ShipDate] ON [Delivery] 
(
	[ShipDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_ShipDate_Model] ON [Delivery] 
(
	[ShipDate] ASC,
	[Model] ASC
)
INCLUDE ( [DeliveryNo],
[Qty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_ShipDate_Status] ON [Delivery] 
(
	[ShipDate] ASC,
	[Status] ASC
)
INCLUDE ( [Model],
[Qty]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [<ProductStatus_Cdt>] ON [ProductStatus] 
(
	[Udt] ASC
)
INCLUDE ( [ProductID],
[Station],
[Status],
[ReworkCode],
[Line],
[TestFailCount],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ProductStatus] ON [ProductStatus] 
(
	[ProductID] ASC,
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_Sys_Name] ON [SysSetting] 
(
	[Name] ASC
)
INCLUDE ( [Value]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ProductAttrLog_ProductID] ON [ProductAttrLog] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductAttr] ON [ProductAttr] 
(
	[Udt] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ProductAttr_ProductID] ON [ProductAttr] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Pizza_Part_PartSn] ON [Pizza_Part] 
(
	[PartSn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Pizza_Part_PizzaID] ON [Pizza_Part] 
(
	[PizzaID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_PartSn_PizzaId] ON [Pizza_Part] 
(
	[PartSn] ASC,
	[PizzaID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [<ProductTestLogBack_Station_Status_Cdt>] ON [ProductTestLogBack] 
(
	[Station] ASC,
	[Status] ASC,
	[Cdt] ASC
)
INCLUDE ( [ID],
[Line]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ProductTestLog_ProductID] ON [ProductTestLog] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_ProductLog_ProductID] ON [ProductLog] 
(
	[ProductID] ASC
)
INCLUDE ( [Model],
[Station],
[Status],
[Line],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductLog_Model] ON [ProductLog] 
(
	[Model] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductLog_ModelStation] ON [ProductLog] 
(
	[Model] ASC,
	[Station] ASC,
	[Cdt] ASC
)
INCLUDE ( [ProductID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductLog_ProductIDStation] ON [ProductLog] 
(
	[ProductID] ASC,
	[Station] ASC
)
INCLUDE ( [Model],
[Status],
[Line],
[Editor],
[Cdt]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductLog_Station] ON [ProductLog] 
(
	[Station] ASC
)
INCLUDE ( [ProductID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_ProductInfo_InfoType_InfoValue] ON [ProductInfo] 
(
	[InfoValue] ASC,
	[InfoType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ProductInfo_ProductID] ON [ProductInfo] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductRepair_ProductID] ON [ProductRepair] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_Part_PartNo] ON [Product_Part] 
(
	[PartNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_Part_PartSn] ON [Product_Part] 
(
	[PartSn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Product_Part_ProductID] ON [Product_Part] 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_ProductTestLog_DefectInfo_ProductTestLogID] ON [ProductTestLog_DefectInfo] 
(
	[ProductTestLogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
   CREATE NONCLUSTERED INDEX [<ProductTestLogBack_DefectInfo_DefectCodeID_TriggerAlarm>] ON [ProductTestLogBack_DefectInfo] 
(
	[ProductTestLogBackID] ASC
)
INCLUDE ( [DefectCodeID],
[TriggerAlarm]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ProductRepairID] ON [ProductRepair_DefectInfo] 
(
	[ProductRepairID] ASC
)
INCLUDE ( [DefectCode],
[Cause],
[Obligation],
[Location],
[Remark]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_DeliveryInfo_DeliveryNo] ON [DeliveryInfo] 
(
	[DeliveryNo] ASC
)
INCLUDE ( [InfoType],
[InfoValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_DeliveryInfo_InfoType] ON [DeliveryInfo] 
(
	[InfoType] ASC
)
INCLUDE ( [DeliveryNo],
[InfoValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_DeliveryInfo_InfoValueInfoType] ON [DeliveryInfo] 
(
	[InfoValue] ASC,
	[InfoType] ASC
)
INCLUDE ( [DeliveryNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_DeliveryNo_InfoType] ON [DeliveryInfo] 
(
	[DeliveryNo] ASC,
	[InfoType] ASC
)
INCLUDE ( [InfoValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Delivery_Pallet_DeliveryNo] ON [Delivery_Pallet] 
(
	[DeliveryNo] ASC
)
INCLUDE ( [PalletNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Delivery_Pallet_PalletNo] ON [Delivery_Pallet] 
(
	[PalletNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_Delivery_Pallet_ShipmentNo] ON [Delivery_Pallet] 
(
	[ShipmentNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [Idx_PalletNo_Delivery] ON [Delivery_Pallet] 
(
	[DeliveryNo] ASC,
	[PalletNo] ASC
)
INCLUDE ( [DeliveryQty],
[Status]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IDX_PCBNo] ON [PCBAttr] 
(
	[PCBNo] ASC
)
INCLUDE ( [AttrName],
[AttrValue]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBRepair_PCBNo] ON [PCBRepair] 
(
	[PCBNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [IX_PCBRepair_TestLogID] ON [PCBRepair] 
(
	[TestLogID] ASC
)
INCLUDE ( [PCBNo]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
CREATE NONCLUSTERED INDEX [PCBRepair_Cdt] ON [PCBRepair] 
(
	[Cdt] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PCBRepair_DefectInfo_PCARepairID] ON [PCBRepair_DefectInfo] 
(
	[PCARepairID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Index]
GO
